// AUTO-GENERATED by scripts/generate-module-registry.js
// Do not edit manually. Run: node scripts/generate-module-registry.js

import { Module } from "../types";


export const contentModules: Module[] = [
];
