// ============================================================================
// Computersysteme & Hardware — Übungsaufgaben
// ============================================================================

import { Exercise } from "./mathExercises";

export type { Exercise };

// ==================== PRACTICE (25 Aufgaben) ====================

export const computersystemePractice: Exercise[] = [
  // hw-1: CPU-Architektur (5 Aufgaben)
  {
    id: "hw-p-1",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Welche Komponente führt arithmetische und logische Operationen in der CPU durch?",
    options: [
      { label: "Steuerwerk", value: "a" },
      { label: "ALU", value: "b" },
      { label: "Register", value: "c" },
      { label: "Cache", value: "d" },
    ],
    correctOption: "b",
    solution: "Die ALU (Arithmetic Logic Unit) ist das Rechenwerk der CPU. Sie führt alle Rechenoperationen durch: Addition, Subtraktion, UND, ODER, NICHT.",
  },
  {
    id: "hw-p-2",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Was ist die Aufgabe des Program Counters (PC)?",
    options: [
      { label: "Speichert Rechenergebnisse", value: "a" },
      { label: "Enthält die Adresse des nächsten Befehls", value: "b" },
      { label: "Decodiert den aktuellen Befehl", value: "c" },
      { label: "Führt Berechnungen durch", value: "d" },
    ],
    correctOption: "b",
    solution: "Der Program Counter (PC) enthält immer die Adresse des nächsten Befehls, der aus dem Speicher geholt werden soll.",
  },
  {
    id: "hw-p-3",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Beschreibe die drei Phasen des Fetch-Decode-Execute-Zyklus in der richtigen Reihenfolge.",
    expectedAnswer: "fetch decode execute",
    hint: "PC → MAR → Speicher → MDR → IR → Decode → Execute",
    solution: "1. FETCH: PC→MAR, Speicher liefert Befehl→MDR→IR, PC wird erhöht. 2. DECODE: Steuerwerk analysiert den Befehl im IR. 3. EXECUTE: ALU führt Operation aus, Ergebnis wird gespeichert.",
  },
  {
    id: "hw-p-4",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "multiple",
    question: "Was ist der Unterschied zwischen CISC und RISC?",
    options: [
      { label: "CISC = einfache Befehle, RISC = komplexe Befehle", value: "a" },
      { label: "CISC = komplexe Befehle variabel lang, RISC = einfache Befehle einheitlich lang", value: "b" },
      { label: "CISC = nur für Server, RISC = nur für Mobilgeräte", value: "c" },
      { label: "Es gibt keinen Unterschied", value: "d" },
    ],
    correctOption: "b",
    solution: "CISC (z.B. Intel/AMD x86) hat komplexe Befehle variabler Länge. RISC (z.B. ARM) hat einfache Befehle einheitlicher Länge — Pipeline-freundlich.",
  },
  {
    id: "hw-p-5",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "multiple",
    question: "Was ist der Von-Neumann-Flaschenhals?",
    options: [
      { label: "Die CPU ist zu langsam für den Speicher", value: "a" },
      { label: "Programm und Daten teilen sich denselben Bus — sequenzieller Zugriff begrenzt Geschwindigkeit", value: "b" },
      { label: "Der Cache ist zu klein", value: "c" },
      { label: "Es gibt zu viele Register", value: "d" },
    ],
    correctOption: "b",
    solution: "Bei Von-Neumann teilen sich Programm und Daten denselben Speicher und Bus. Die CPU muss abwechselnd Befehle und Daten holen — das erzeugt einen Flaschenhals.",
  },

  // hw-2: Busse & Takt (3 Aufgaben)
  {
    id: "hw-p-6",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Welche drei Arten von Bussen gibt es?",
    options: [
      { label: "Schnellbus, Langsambus, Cachebus", value: "a" },
      { label: "Adressbus, Datenbus, Steuerbus", value: "b" },
      { label: "CPU-Bus, RAM-Bus, GPU-Bus", value: "c" },
      { label: "USB, SATA, PCIe", value: "d" },
    ],
    correctOption: "b",
    solution: "Die drei Busse: Adressbus (CPU→Speicher, bestimmt Adressraum), Datenbus (bidirektional, Datenübertragung), Steuerbus (Signale wie Lesen/Schreiben/Interrupt).",
  },
  {
    id: "hw-p-7",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Ein Prozessor hat 32 Adressleitungen. Wie viele Bytes kann er maximal adressieren?",
    expectedAnswer: "4294967296",
    tolerance: 1,
    hint: "Formel: 2^n Bytes, wobei n = Anzahl Adressleitungen",
    solution: "2^32 = 4.294.967.296 Bytes = 4 GB. Der 32-Bit-Adressraum ist auf 4 GB begrenzt — ein Grund für 64-Bit-Systeme.",
  },
  {
    id: "hw-p-8",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "multiple",
    question: "Eine CPU hat 4 GHz Taktfrequenz und IPC = 3. Wie viele Befehle pro Sekunde?",
    options: [
      { label: "4 Milliarden", value: "a" },
      { label: "12 Milliarden", value: "b" },
      { label: "1,33 Milliarden", value: "c" },
      { label: "7 Milliarden", value: "d" },
    ],
    correctOption: "b",
    solution: "Befehle/Sekunde = Taktfrequenz × IPC = 4 GHz × 3 = 12 Milliarden Befehle pro Sekunde.",
  },

  // hw-3: Eingabegeräte (3 Aufgaben)
  {
    id: "hw-p-9",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Welcher Authentifizierungsfaktor ist Fingerabdruck?",
    options: [
      { label: "Was man weiß", value: "a" },
      { label: "Was man hat", value: "b" },
      { label: "Was man ist", value: "c" },
      { label: "Was man tut", value: "d" },
    ],
    correctOption: "c",
    solution: "Biometrie = 'was man IST'. Die drei Faktoren: 'was man weiß' (Passwort), 'was man hat' (Token), 'was man ist' (Biometrie).",
  },
  {
    id: "hw-p-10",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Was ist der Unterschied zwischen RFID und NFC?",
    options: [
      { label: "RFID und NFC sind identisch", value: "a" },
      { label: "NFC ist eine Teilmenge von RFID mit kürzerer Reichweite (<4cm) und bidirektional", value: "b" },
      { label: "RFID ist moderner als NFC", value: "c" },
      { label: "NFC funktioniert nur mit Kabel", value: "d" },
    ],
    correctOption: "b",
    solution: "NFC ist eine Teilmenge von RFID. Reichweite <4cm, bidirektional, sicherer. RFID: bis 12m, meist einseitig. NFC = kontaktloses Bezahlen.",
  },
  {
    id: "hw-p-11",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "multiple",
    question: "Welches biometrische Verfahren hat die höchste Sicherheit?",
    options: [
      { label: "Fingerabdruck", value: "a" },
      { label: "Gesichtserkennung", value: "b" },
      { label: "Iris-Scan", value: "c" },
      { label: "Stimmerkennung", value: "d" },
    ],
    correctOption: "c",
    solution: "Iris-Scan hat die höchste Genauigkeit und Sicherheit — wird in Hochsicherheitsbereichen eingesetzt. Fingerabdruck ist mittel-hoch, Gesichtserkennung hoch, Stimmerkennung mittel.",
  },

  // hw-4: Ausgabegeräte (3 Aufgaben)
  {
    id: "hw-p-12",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Welches Druckverfahren nutzt Toner (Pulver)?",
    options: [
      { label: "Tintenstrahldrucker", value: "a" },
      { label: "Laserdrucker", value: "b" },
      { label: "Nadeldrucker", value: "c" },
      { label: "Thermischer Drucker", value: "d" },
    ],
    correctOption: "b",
    solution: "Laserdrucker nutzen Toner (Pulver), das durch Laser auf eine Trommel übertragen und durch Hitze fixiert wird. NICHT Tinte!",
  },
  {
    id: "hw-p-13",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Was ist der Vorteil von OLED gegenüber LCD?",
    options: [
      { label: "Günstiger in der Herstellung", value: "a" },
      { label: "Perfektes Schwarz (selbstleuchtend), dünn, hoher Kontrast", value: "b" },
      { label: "Kein Burn-in möglich", value: "c" },
      { label: "Höhere Helligkeit bei Sonnenlicht", value: "d" },
    ],
    correctOption: "b",
    solution: "OLED-Pixel leuchten selbst — bei Schwarz sind sie aus = perfektes Schwarz, hoher Kontrast, dünn. Nachteil: Burn-in-Gefahr, teurer.",
  },
  {
    id: "hw-p-14",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "multiple",
    question: "Was bedeutet 'dpi' bei einem Drucker?",
    options: [
      { label: "Data Processing Interface", value: "a" },
      { label: "Dots Per Inch — Druckauflösung", value: "b" },
      { label: "Digital Print Integration", value: "c" },
      { label: "Druckparameter-Index", value: "d" },
    ],
    correctOption: "b",
    solution: "DPI = Dots Per Inch = Punkte pro Zoll. 300 dpi reicht für Text, 1200+ dpi für Fotos. Höher = feinerer Druck.",
  },

  // hw-5: Speichermedien & RAID (4 Aufgaben)
  {
    id: "hw-p-15",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Was ist der Hauptunterschied zwischen HDD und SSD?",
    options: [
      { label: "HDD ist schneller als SSD", value: "a" },
      { label: "SSD hat keine mechanischen Teile — schneller, robuster, teurer", value: "b" },
      { label: "SSD nutzt Magnetismus, HDD Halbleiter", value: "c" },
      { label: "Es gibt keinen Unterschied", value: "d" },
    ],
    correctOption: "b",
    solution: "SSD: NAND-Flash (Halbleiter), keine Mechanik, ~0.1ms Zugriff. HDD: Magnetische Scheiben, Mechanik, ~5-10ms Zugriff, günstiger pro GB.",
  },
  {
    id: "hw-p-16",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Wie viel nutzbare Kapazität hat ein RAID 5 mit 5 Platten à 2 TB?",
    expectedAnswer: "8",
    hint: "RAID 5: nutzbare Kapazität = (n-1) × Plattengröße",
    solution: "RAID 5: (n-1) × Plattengröße = (5-1) × 2 TB = 8 TB. Eine Platte wird für die verteilte Parität verwendet.",
  },
  {
    id: "hw-p-17",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "multiple",
    question: "Welches RAID-Level bietet den besten Kompromiss aus Leistung und Sicherheit?",
    options: [
      { label: "RAID 0", value: "a" },
      { label: "RAID 1", value: "b" },
      { label: "RAID 5", value: "c" },
      { label: "RAID 10", value: "d" },
    ],
    correctOption: "c",
    solution: "RAID 5: Striping + verteilte Parität. Gute Lesegeschwindigkeit, 1 Platte darf ausfallen, effiziente Kapazitätsnutzung. RAID 10 ist besser aber teurer.",
  },
  {
    id: "hw-p-18",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "input",
    question: "Ein Unternehmen braucht 8 TB Speicher mit Ausfallsicherheit (1 Platte darf ausfallen). Welches RAID mit 4-TB-Platten und wie viele Platten?",
    expectedAnswer: "raid 5",
    hint: "RAID 5: nutzbare Kapazität = (n-1) × Platte. 8 TB = (n-1) × 4 TB → n = 3",
    solution: "RAID 5 mit 3 Platten à 4 TB: (3-1) × 4 TB = 8 TB nutzbar. RAID 5 erlaubt 1 Platte Ausfall. Alternativ: RAID 1 mit 4 Platten (aber nur 8 TB bei 16 TB gesamt).",
  },

  // hw-6: Speicherverwaltung (4 Aufgaben)
  {
    id: "hw-p-19",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Was ist der Unterschied zwischen SRAM und DRAM?",
    options: [
      { label: "SRAM ist langsamer aber günstiger", value: "a" },
      { label: "SRAM ist schneller, teuer, für Cache. DRAM ist langsamer, günstig, für RAM, braucht Refresh", value: "b" },
      { label: "DRAM behält Daten ohne Strom", value: "c" },
      { label: "SRAM und DRAM sind identisch", value: "d" },
    ],
    correctOption: "b",
    solution: "SRAM: Flip-Flop (6 Transistoren), ~1ns, teuer, für Cache. DRAM: Kondensator (1 Transistor), ~100ns, günstig, braucht Refresh alle ~64ms, für RAM.",
  },
  {
    id: "hw-p-20",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "input",
    question: "Nenne die Speicherhierarchie von schnell nach langsam (6 Ebenen).",
    expectedAnswer: "register l1 l2 l3 ram ssd hdd",
    hint: "Merksatz: Rein Lustig Lernen Lektionen Richtig Schnell",
    solution: "Register → L1 Cache → L2 Cache → L3 Cache → RAM → SSD → HDD. Je schneller, desto teurer und kleiner.",
  },
  {
    id: "hw-p-21",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Ein System hat 8 GB RAM und die Seitengröße beträgt 4 KB. Wie viele Seitenrahmen gibt es?",
    expectedAnswer: "2097152",
    tolerance: 1,
    hint: "Seitenrahmen = RAM-Größe / Seitengröße. 8 GB = 8 × 1024 × 1024 × 1024 Bytes",
    solution: "8 GB / 4 KB = (8 × 1024³) / (4 × 1024) = 8.589.934.592 / 4.096 = 2.097.152 Seitenrahmen.",
  },
  {
    id: "hw-p-22",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "multiple",
    question: "Was passiert bei einem Page Fault?",
    options: [
      { label: "Die CPU stürzt ab", value: "a" },
      { label: "OS muss die angefragte Seite von der Festplatte in den RAM laden — langsam!", value: "b" },
      { label: "Der Cache wird geleert", value: "c" },
      { label: "Ein Register wird überschrieben", value: "d" },
    ],
    correctOption: "b",
    solution: "Page Fault: Zugriff auf Seite, die nicht im RAM ist. OS muss sie von Festplatte (SSD/HDD) laden — ~100x langsamer als RAM-Zugrift. Wenn RAM voll: eine andere Seite wird ausgelagert.",
  },

  // hw-7: Betriebssysteme (3 Aufgaben)
  {
    id: "hw-p-23",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "Was ist der Kernel eines Betriebssystems?",
    options: [
      { label: "Die grafische Oberfläche", value: "a" },
      { label: "Der Kern des OS — direkter Hardwarezugriff, Prozess- und Speicherverwaltung", value: "b" },
      { label: "Ein Virenscanner", value: "c" },
      { label: "Der Webbrowser", value: "d" },
    ],
    correctOption: "b",
    solution: "Der Kernel ist der Kern des Betriebssystems mit direktem Hardwarezugriff. Er verwaltet Prozesse, Speicher, Geräte und Sicherheit.",
  },
  {
    id: "hw-p-24",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "multiple",
    question: "BIOS vs. UEFI — was ist moderner?",
    options: [
      { label: "BIOS ist moderner", value: "a" },
      { label: "UEFI ist moderner: 32/64-Bit, GPT, grafisch, Secure Boot", value: "b" },
      { label: "Beide sind gleich alt", value: "c" },
      { label: "BIOS und UEFI sind identisch", value: "d" },
    ],
    correctOption: "b",
    solution: "UEFI ersetzt BIOS: 32/64-Bit (statt 16-Bit), GPT (statt MBR, max. 9.4 ZB), grafische Oberfläche, Secure Boot, Netzwerk-Support.",
  },
  {
    id: "hw-p-25",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "multiple",
    question: "Was ist der Unterschied zwischen Preemptive und Cooperativem Multitasking?",
    options: [
      { label: "Preemptive: OS entscheidet Umschaltung. Cooperativ: Prozess gibt freiwillig ab.", value: "a" },
      { label: "Cooperatives ist schneller", value: "b" },
      { label: "Preemptive funktioniert nur mit einem Kern", value: "c" },
      { label: "Es gibt keinen Unterschied", value: "d" },
    ],
    correctOption: "a",
    solution: "Preemptive: OS erzwingt Umschaltung per Zeitscheibe (modern: Windows, Linux). Cooperativ: Prozess muss freiwillig CPU abgeben (veraltet, anfällig für Einfrieren).",
  },
];

// ==================== EXAM (10 Aufgaben) ====================

export const computersystemeExam: Exercise[] = [
  {
    id: "hw-e-1",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Erkläre den Fetch-Decode-Execute-Zyklus anhand eines ADD-Befehls (ADD AX, BX).",
    expectedAnswer: "fetch decode execute",
    solution: "FETCH: PC→MAR, Befehl 'ADD AX,BX' aus Speicher→MDR→IR, PC++. DECODE: Steuerwerk erkennt Opcode ADD, Operanden AX und BX. EXECUTE: ALU addiert AX+BX, Ergebnis in AX gespeichert.",
  },
  {
    id: "hw-e-2",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "input",
    question: "Ein Unternehmen braucht 8 TB Speicher mit Ausfallsicherheit. Welches RAID und wie viele Platten bei 4 TB pro Platte?",
    expectedAnswer: "raid 5",
    solution: "RAID 5 mit 3 Platten à 4 TB: (3-1) × 4 TB = 8 TB nutzbar. 1 Platte darf ausfallen (verteilte Parität). Alternativ RAID 6 mit 4 Platten für höhere Sicherheit.",
  },
  {
    id: "hw-e-3",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Ein System hat 4 GB RAM und die Page Size ist 4 KB. Wie viele Seitenrahmen gibt es?",
    expectedAnswer: "1048576",
    tolerance: 1,
    solution: "4 GB / 4 KB = (4 × 1024³) / (4 × 1024) = 4.294.967.296 / 4.096 = 1.048.576 Seitenrahmen.",
  },
  {
    id: "hw-e-4",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Vergleiche Typ-1 und Typ-2 Hypervisor in Bezug auf Performance und Sicherheit.",
    expectedAnswer: "typ 1 typ 2",
    solution: "Typ 1 (Bare-Metal): Direkt auf Hardware, bessere Performance, sicherere Isolation (z.B. ESXi, Hyper-V). Typ 2 (Hosted): Auf Host-OS, mehr Overhead, weniger performant, einfacher zu installieren (z.B. VirtualBox).",
  },
  {
    id: "hw-e-5",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "input",
    question: "Bei 80% Parallelisierung: Was ist der maximale Speedup mit 4 Prozessoren nach Amdahl?",
    expectedAnswer: "2.5",
    tolerance: 0.1,
    solution: "Speedup = 1 / ((1-p) + p/n) = 1 / ((1-0.8) + 0.8/4) = 1 / (0.2 + 0.2) = 1 / 0.4 = 2.5. Maximaler Speedup (n→∞) = 1/(1-0.8) = 5.",
  },
  {
    id: "hw-e-6",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "multiple",
    question: "Welches Speichermedium eignet sich für ein NAS im Unternehmen mit 24/7-Betrieb?",
    options: [
      { label: "Consumer-SSD", value: "a" },
      { label: "Enterprise-HDD oder NAS-HDD (z.B. WD Red, Seagate IronWolf)", value: "b" },
      { label: "USB-Stick", value: "c" },
      { label: "Blu-ray", value: "d" },
    ],
    correctOption: "b",
    solution: "NAS-festige HDDs (WD Red, Seagate IronWolf) sind für 24/7-Betrieb ausgelegt, vibrationsresistent und haben längere Garantie. Consumer-SSDs sind nicht für Dauerbetrieb optimiert.",
  },
  {
    id: "hw-e-7",
    lessonId: "ihk-computersysteme",
    difficulty: 3,
    type: "input",
    question: "Ein 64-Bit-Prozessor hat 48 Adressleitungen. Wie viel RAM kann er maximal adressieren?",
    expectedAnswer: "256",
    solution: "2^48 Bytes = 281.474.976.710.656 Bytes = 256 TB. Die 64-Bit-Architektur erlaubt theoretisch 16 EB, aber physisch oft nur 48 Adressleitungen.",
  },
  {
    id: "hw-e-8",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Erkläre den Unterschied zwischen SRAM und DRAM und wo werden sie eingesetzt?",
    expectedAnswer: "sram dram",
    solution: "SRAM: Flip-Flop, schnell (~1ns), teuer, kein Refresh → für Cache (L1/L2/L3). DRAM: Kondensator, langsamer (~100ns), günstig, Refresh nötig → für Hauptspeicher (RAM).",
  },
  {
    id: "hw-e-9",
    lessonId: "ihk-computersysteme",
    difficulty: 1,
    type: "input",
    question: "Nenne 3 Maßnahmen für Green IT in einem Rechenzentrum.",
    expectedAnswer: "green it",
    solution: "1. Server-Virtualisierung (weniger physische Server). 2. Free Cooling (Außenluft statt Klimaanlage). 3. Erneuerbare Energien nutzen. Weitere: Effiziente Netzteile (80 PLUS), Server-Konsolidierung, Recycling.",
  },
  {
    id: "hw-e-10",
    lessonId: "ihk-computersysteme",
    difficulty: 2,
    type: "input",
    question: "Was ist der Unterschied zwischen BIOS und UEFI?",
    expectedAnswer: "bios uefi",
    solution: "BIOS: 16-Bit, MBR (max. 2 TB), textbasiert, langsamer Boot. UEFI: 32/64-Bit, GPT (max. 9.4 ZB), grafisch, Secure Boot, schneller Boot, Netzwerk-Support.",
  },
];
