import { Exercise } from "./mathExercises";

// ==================== IT-SICHERHEIT ====================

export const itSicherheitPractice: Exercise[] = [
  // === Schwierigkeit 1: Grundlagen ===
  {
    id: "is-1",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "multiple",
    question: "Was beschreibt die CIA-Triade?",
    options: [
      { label: "Confidentiality, Integrity, Availability", value: "a" },
      { label: "Control, Identification, Authentication", value: "b" },
      { label: "Configuration, Installation, Administration", value: "c" },
      { label: "Certification, Inspection, Authorization", value: "d" },
    ],
    correctOption: "a",
    solution: "Die CIA-Triade steht für Vertraulichkeit (Confidentiality), Integrität (Integrity) und Verfügbarkeit (Availability) — die drei Grundpfeiler der IT-Sicherheit.",
  },
  {
    id: "is-2",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "input",
    question: "Wie viele Zeichen sollte ein sicheres Passwort MINDESTENS haben?",
    expectedAnswer: "12",
    format: "Ganze Zahl",
    solution: "Experten empfehlen mindestens 12 Zeichen. Längere Passwörter sind exponentiell schwerer zu knacken.",
  },
  {
    id: "is-3",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "multiple",
    question: "Was ist der Unterschied zwischen Authentifizierung und Autorisierung?",
    options: [
      { label: "Authentifizierung = Wer bist du? Autorisierung = Was darfst du?", value: "a" },
      { label: "Authentifizierung = Was darfst du? Autorisierung = Wer bist du?", value: "b" },
      { label: "Beide Begriffe bedeuten dasselbe", value: "c" },
      { label: "Authentifizierung ist verschlüsselt, Autorisierung nicht", value: "d" },
    ],
    correctOption: "a",
    solution: "Authentifizierung prüft die IDENTITÄT (Wer bist du?), Autorisierung prüft die BERECHTIGUNG (Was darfst du?).",
  },
  {
    id: "is-4",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "multiple",
    question: "Welche Art von Malware verschlüsselt Daten und verlangt Lösegeld?",
    options: [
      { label: "Trojaner", value: "a" },
      { label: "Wurm", value: "b" },
      { label: "Ransomware", value: "c" },
      { label: "Spyware", value: "d" },
    ],
    correctOption: "c",
    solution: "Ransomware verschlüsselt die Dateien des Opfers und fordert eine Zahlung (meist in Kryptowährung) für den Entschlüsselungskey.",
  },
  {
    id: "is-5",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "input",
    question: "Was besagt die 3-2-1-Backup-Regel? Wie viele Kopien sollte man haben?",
    expectedAnswer: "3",
    format: "Ganze Zahl",
    solution: "3-2-1-Regel: 3 Kopien der Daten, auf 2 verschiedenen Medien, 1 davon extern (offsite).",
  },
  {
    id: "is-6",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "multiple",
    question: "Was macht ein Hashing-Algorithmus (z.B. SHA-256)?",
    options: [
      { label: "Verschlüsselt Daten symmetrisch", value: "a" },
      { label: "Erzeugt einen eindeutigen Festwert fester Länge", value: "b" },
      { label: "Komprimiert Daten auf die Hälfte", value: "c" },
      { label: "Signiert digital mit einem Private Key", value: "d" },
    ],
    correctOption: "b",
    solution: "Hashing erzeugt aus beliebig langen Daten einen eindeutigen Hash fester Länge (SHA-256 = 256 Bit). Es ist EINWEG — man kann den Hash nicht zurückrechnen.",
  },
  {
    id: "is-7",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "multiple",
    question: "Was ist ein Man-in-the-Middle-Angriff (MITM)?",
    options: [
      { label: "Ein Virus der sich in der Mitte einer Datei versteckt", value: "a" },
      { label: "Ein Angreifer der sich zwischen zwei Kommunikationspartner schaltet", value: "b" },
      { label: "Ein Angriff auf die Mitte eines Netzwerks", value: "c" },
      { label: "Ein Trojaner der Admin-Rechte erlangt", value: "d" },
    ],
    correctOption: "b",
    solution: "Bei einem MITM-Angriff positioniert sich der Angreifer zwischen Sender und Empfänger und kann den Datenverkehr mitlesen oder manipulieren.",
  },
  {
    id: "is-8",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "input",
    question: "Welcher Port wird standardmäßig für HTTPS verwendet?",
    expectedAnswer: "443",
    format: "Ganze Zahl",
    solution: "HTTPS nutzt Port 443 (TLS/SSL). HTTP nutzt Port 80.",
  },
  // === Schwierigkeit 2: Angriffe & Schutzmaßnahmen ===
  {
    id: "is-9",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Was ist eine SQL-Injection?",
    options: [
      { label: "Ein Virus der SQL-Datenbanken befällt", value: "a" },
      { label: "Einschleusen von SQL-Befehlen über Eingabefelder", value: "b" },
      { label: "Ein Backup einer SQL-Datenbank", value: "c" },
      { label: "Eine Verschlüsselungsmethode für SQL", value: "d" },
    ],
    correctOption: "b",
    solution: "SQL-Injection: Der Angreifer gibt SQL-Code in Eingabefelder ein, der dann vom Server ausgeführt wird. Schutz: Prepared Statements, Input Validation.",
  },
  {
    id: "is-10",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Was ist der Unterschied zwischen symmetrischer und asymmetrischer Verschlüsselung?",
    options: [
      { label: "Symmetrisch = 1 Key, Asymmetrisch = 2 Keys (Public + Private)", value: "a" },
      { label: "Symmetrisch = schneller, Asymmetrisch = langsamer — gleiche Keys", value: "b" },
      { label: "Symmetrisch ist unsicherer als asymmetrisch", value: "c" },
      { label: "Es gibt keinen Unterschied", value: "d" },
    ],
    correctOption: "a",
    solution: "Symmetrisch: ein gemeinsamer Key für Ver- und Entschlüsselung (z.B. AES). Asymmetrisch: Public Key zum Verschlüsseln, Private Key zum Entschlüsseln (z.B. RSA).",
  },
  {
    id: "is-11",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "input",
    question: "Was steht hinter der Abkürzung XSS?",
    expectedAnswer: "Cross-Site Scripting",
    format: "Text",
    solution: "XSS = Cross-Site Scripting. Der Angreifer schleust JavaScript-Code in Webseiten ein, der im Browser des Opfers ausgeführt wird.",
  },
  {
    id: "is-12",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Was macht eine Firewall?",
    options: [
      { label: "Verschlüsselt den gesamten Netzwerkverkehr", value: "a" },
      { label: "Filtert Netzwerkverkehr nach definierten Regeln", value: "b" },
      { label: "Ersetzt den Virenscanner", value: "c" },
      { label: "Speichert Passwörter sicher", value: "d" },
    ],
    correctOption: "b",
    solution: "Eine Firewall filtert den Netzwerkverkehr anhand von Regeln (z.B. erlaubte/verbotene Ports, IP-Adressen). Sie schützt vor unberechtigtem Zugriff.",
  },
  {
    id: "is-13",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Was ist Phishing?",
    options: [
      { label: "Ein Angriff auf Netzwerkinfrastruktur", value: "a" },
      { label: "Das Ausspähen von Passwörtern über gefälschte E-Mails/Webseiten", value: "b" },
      { label: "Eine Methode zum Passwort-Hashing", value: "c" },
      { label: "Ein Verschlüsselungsverfahren", value: "d" },
    ],
    correctOption: "b",
    solution: "Phishing: Der Angreifer täuscht dem Opfer eine vertrauenswürdige Quelle vor (z.B. Bank, E-Mail-Provider), um an sensible Daten zu kommen.",
  },
  {
    id: "is-14",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "input",
    question: "Was ist der Zweck von Salting beim Passwort-Hashing?",
    options: [
      { label: "Die Hashes kürzer zu machen", value: "a" },
      { label: "Gleiche Passwörter erzeugen unterschiedliche Hashes", value: "b" },
      { label: "Die Verschlüsselung zu beschleunigen", value: "c" },
      { label: "Passwörter lesbar zu speichern", value: "d" },
    ],
    correctOption: "b",
    solution: "Salting: Vor dem Hashen wird ein zufälliger Wert (Salt) angehängt. So erzeugen gleiche Passwörter unterschiedliche Hashes — Rainbow-Table-Angriffe werden nutzlos.",
  },
  {
    id: "is-15",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Was ist eine DMZ (Demilitarisierte Zone)?",
    options: [
      { label: "Ein gesicherter Bereich zwischen internem Netz und Internet", value: "a" },
      { label: "Ein Netzwerk ohne Firewall", value: "b" },
      { label: "Ein verschlüsseltes WLAN", value: "c" },
      { label: "Ein Backup-Rechenzentrum", value: "d" },
    ],
    correctOption: "a",
    solution: "Die DMZ ist ein abgeschirmtes Netzwerk zwischen dem internen Netz und dem Internet. Öffentliche Server (Web, Mail) stehen hier — kompromittiert ist trotzdem das interne Netz geschützt.",
  },
  {
    id: "is-16",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "input",
    question: "Was steht hinter der Abkürzung CSRF?",
    expectedAnswer: "Cross-Site Request Forgery",
    format: "Text",
    solution: "CSRF = Cross-Site Request Forgery. Der Angreifer lässt den Browser des Opfers unbemerkt eine Aktion auf einer anderen Webseite ausführen (z.B. Überweisung).",
  },
  // === Schwierigkeit 3: OWASP & Praxis ===
  {
    id: "is-17",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Ein Login-Formular prüft Benutzereingaben nicht. Welche Attacke ist am wahrscheinlichsten?",
    options: [
      { label: "DDoS", value: "a" },
      { label: "SQL-Injection", value: "b" },
      { label: "Phishing", value: "c" },
      { label: "Man-in-the-Middle", value: "d" },
    ],
    correctOption: "b",
    solution: "Fehlende Input-Validierung ist die #1 Voraussetzung für SQL-Injection. Der Angreifer kann SQL-Befehle direkt in die Eingabefelder schreiben.",
  },
  {
    id: "is-18",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Welche Gegenmaßnahme verhindert SQL-Injection am zuverlässigsten?",
    options: [
      { label: "Passwörter hashen", value: "a" },
      { label: "HTTPS aktivieren", value: "b" },
      { label: "Prepared Statements / Parameterized Queries verwenden", value: "c" },
      { label: "Eine Firewall installieren", value: "d" },
    ],
    correctOption: "c",
    solution: "Prepared Statements trennen Code und Daten. Die Eingabe wird NIE als SQL-Code interpretiert — die effektivste Schutzmaßnahme.",
  },
  {
    id: "is-19",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Ein Nutzer bekommt eine E-Mail: 'Ihr Paket konnte nicht zugestellt werden. Klicken Sie hier.' Die URL zeigt auf eine unbekannte Domain. Was ist das?",
    options: [
      { label: "Ein normaler Kundenservice", value: "a" },
      { label: "Spear-Phishing", value: "b" },
      { label: "Phishing", value: "c" },
      { label: "Social Engineering per Telefon", value: "d" },
    ],
    correctOption: "c",
    solution: "Klassisches Phishing: eine gefälschte E-Mail mit Link auf eine betrügerische Seite. Spear-Phishing wäre zielgerichtet auf eine bestimmte Person.",
  },
  {
    id: "is-20",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "input",
    question: "Wie viele Positionen hat die OWASP Top 10 Liste (Stand 2021)?",
    expectedAnswer: "10",
    format: "Ganze Zahl",
    solution: "Die OWASP Top 10 enthält — wie der Name sagt — die 10 kritischsten Web-Sicherheitsrisiken.",
  },
  {
    id: "is-21",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Was ist der Unterschied zwischen IDS und IPS?",
    options: [
      { label: "IDS erkennt Angriffe, IPS erkennt UND blockiert sie automatisch", value: "a" },
      { label: "IDS ist für interne Netze, IPS für externe", value: "b" },
      { label: "Beide sind identisch", value: "c" },
      { label: "IDS verschlüsselt, IPS entschlüsselt", value: "d" },
    ],
    correctOption: "a",
    solution: "IDS (Intrusion Detection System) warnt nur. IPS (Intrusion Prevention System) erkennt und BLOCKIERT Angriffe automatisch.",
  },
  {
    id: "is-22",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Ein Mitarbeiter gibt am Telefon seine PIN weiter, weil sich jemand als IT-Abteilung ausgibt. Was ist das?",
    options: [
      { label: "Phishing", value: "a" },
      { label: "Pretexting (Social Engineering)", value: "b" },
      { label: "Brute-Force", value: "c" },
      { label: "Keylogging", value: "d" },
    ],
    correctOption: "b",
    solution: "Pretexting: Der Angreifer erfindet einen Vorwand (Prätext), um an Informationen zu kommen. Hier: Fake-Anruf als IT-Abteilung.",
  },
  {
    id: "is-23",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "input",
    question: "Welches Protokoll wird für ein sicheres VPN verwendet (Abkürzung)?",
    expectedAnswer: "IPSec",
    format: "Text",
    solution: "IPSec (Internet Protocol Security) ist das gängigste VPN-Protokoll. Alternatien: OpenVPN, WireGuard.",
  },
  {
    id: "is-24",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Was empfiehlt das BSI IT-Grundschutz-Konzept?",
    options: [
      { label: "Alle Systeme gleich absichern", value: "a" },
      { label: "Standardisierte Sicherheitsmaßnahmen für typische IT-Strukturen", value: "b" },
      { label: "Nur Firewalls einsetzen", value: "c" },
      { label: "Sicherheit nur für Server, nicht für Clients", value: "d" },
    ],
    correctOption: "b",
    solution: "BSI IT-Grundschutz bietet standardisierte Bausteine mit Schutzmaßnahmen für typische IT-Umgebungen — ein systematischer Ansatz zur Absicherung.",
  },
];

export const itSicherheitExam: Exercise[] = [
  {
    id: "is-e1",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Welches Prinzip besagt, dass ein Benutzer nur die Berechtigungen haben sollte, die er für seine Arbeit benötigt?",
    options: [
      { label: "Defense in Depth", value: "a" },
      { label: "Need-to-know / Least Privilege", value: "b" },
      { label: "Separation of Duties", value: "c" },
      { label: "Fail-Safe Defaults", value: "d" },
    ],
    correctOption: "b",
    solution: "Least Privilege: Jeder Benutzer bekommt nur die minimal nötigen Rechte. So wird bei einem Kompromittierung der Schaden begrenzt.",
  },
  {
    id: "is-e2",
    lessonId: "ihk-it-sicherheit",
    difficulty: 1,
    type: "multiple",
    question: "Was bedeutet Verfügbarkeit (Availability) in der CIA-Triade?",
    options: [
      { label: "Daten sind verschlüsselt", value: "a" },
      { label: "Systeme und Daten sind zugänglich wenn sie gebraucht werden", value: "b" },
      { label: "Daten sind nicht verändert worden", value: "c" },
      { label: "Nur autorisierte Personen haben Zugriff", value: "d" },
    ],
    correctOption: "b",
    solution: "Verfügbarkeit = Systeme und Daten sind für autorisiutzer stets zugänglich. DDoS-Angriffe zielen z.B. gegen die Verfügbarkeit.",
  },
  {
    id: "is-e3",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Ein Webshop zeigt in der URL: `shop.de/product?id=1`. Welche Angriffsart ist hier möglich?",
    options: [
      { label: "Cross-Site Scripting (XSS)", value: "a" },
      { label: "SQL-Injection über die URL-Parameter", value: "b" },
      { label: "DDoS", value: "c" },
      { label: "Phishing", value: "d" },
    ],
    correctOption: "b",
    solution: "URL-Parameter wie `id=1` können für SQL-Injection missbraucht werden: `id=1 OR 1=1`. Schutz: Prepared Statements.",
  },
  {
    id: "is-e4",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "input",
    question: "Wie nennt man den Prozess, bei dem Passwörter durch systematisches Ausprobieren geknackt werden?",
    expectedAnswer: "Brute-Force",
    format: "Text",
    solution: "Brute-Force: Alle möglichen Kombinationen werden durchprobiert. Schutz: lange Passwörter, Account-Lockout, Captcha.",
  },
  {
    id: "is-e5",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Was ist ein Zero-Day-Exploit?",
    options: [
      { label: "Ein Angriff der am ersten Tag nach der Installation stattfindet", value: "a" },
      { label: "Ein Exploit für eine Schwachstelle, für die es noch keinen Patch gibt", value: "b" },
      { label: "Ein Angriff mit null Schaden", value: "c" },
      { label: "Ein Test der keine Schwachstellen findet", value: "d" },
    ],
    correctOption: "b",
    solution: "Zero-Day: Die Schwachstelle ist noch nicht bekannt (0 Tage seit Entdeckung) — es gibt keinen Patch. Besonders gefährlich.",
  },
  {
    id: "is-e6",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Welches Protokoll sorgt für verschlüsselte Webseiten-Übertragung?",
    options: [
      { label: "HTTP", value: "a" },
      { label: "FTP", value: "b" },
      { label: "TLS/SSL (HTTPS)", value: "c" },
      { label: "SMTP", value: "d" },
    ],
    correctOption: "c",
    solution: "TLS (Transport Layer Security) verschlüsselt die Verbindung zwischen Browser und Server — erkannt am https:// und Schloss-Symbol.",
  },
  {
    id: "is-e7",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Ein Mitarbeiter öffnet einen USB-Stick mit 'Gehaltsliste_2024.pdf.exe'. Was für ein Angriff?",
    options: [
      { label: "Phishing", value: "a" },
      { label: "Baiting (Social Engineering)", value: "b" },
      { label: "SQL-Injection", value: "c" },
      { label: "DDoS", value: "d" },
    ],
    correctOption: "b",
    solution: "Baiting: Lockmittel (hier: vermeintliche Gehaltsliste) wird ausgelegt. Die .exe-Datei ist Malware. Social Engineering über Neugier.",
  },
  {
    id: "is-e8",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "input",
    question: "Was steht hinter der Abkürzung VPN?",
    expectedAnswer: "Virtual Private Network",
    format: "Text",
    solution: "VPN = Virtual Private Network. Erzeugt einen verschlüsselten Tunnel durch das Internet — wichtig für remote Arbeit.",
  },
  {
    id: "is-e9",
    lessonId: "ihk-it-sicherheit",
    difficulty: 3,
    type: "multiple",
    question: "Welche OWASP-Top-10-Schwachstelle erlaubt es einem Angreifer, eigenen JavaScript-Code im Browser anderer Nutzer auszuführen?",
    options: [
      { label: "Injection", value: "a" },
      { label: "Broken Authentication", value: "b" },
      { label: "Cross-Site Scripting (XSS)", value: "c" },
      { label: "Insecure Deserialization", value: "d" },
    ],
    correctOption: "c",
    solution: "XSS erlaubt das Einschleusen von JavaScript in Webseiten, das dann im Browser anderer Nutzer ausgeführt wird. Schutz: Output Encoding, CSP.",
  },
  {
    id: "is-e10",
    lessonId: "ihk-it-sicherheit",
    difficulty: 2,
    type: "multiple",
    question: "Was ist der Zweck einer digitalen Signatur?",
    options: [
      { label: "Daten verschlüsseln", value: "a" },
      { label: "Authentizität und Integrität eines Dokuments nachweisen", value: "b" },
      { label: "Passwörter sicher speichern", value: "c" },
      { label: "Netzwerkverkehr filtern", value: "d" },
    ],
    correctOption: "b",
    solution: "Digitale Signatur: Der Sender signiert mit seinem Private Key. Der Empfänger prüft mit dem Public Key — beweist Authentizität und Unverändertheit.",
  },
];
