// Interaktive Mathe-Aufgaben für alle Module
export interface Exercise {
  id: string;
  lessonId: string;
  difficulty: 1 | 2 | 3;
  type: 'input' | 'multiple';
  question: string;
  hint?: string;
  expectedAnswer?: string;
  tolerance?: number;
  format?: string;
  options?: { label: string; value: string }[];
  correctOption?: string;
  solution: string;
}

// ==================== MATHE GRUNDLAGEN ====================

export const grundlagenExercises: Exercise[] = [
  // ===== m-grundlagen-mengen (mg1, mg2, mg3, mg4) =====
  // mg1: Mengen
  {
    id: "gr-mengen-1",
    lessonId: "m-grundlagen-mengen",
    difficulty: 1,
    type: "multiple",
    question: "Welche Menge ist eine Teilmenge von $A = \\{1, 2, 3\\}$?",
    options: [
      { label: "$\\{1, 4\\}$", value: "a" },
      { label: "$\\{1, 2\\}$", value: "b" },
      { label: "$\\{4, 5, 6\\}$", value: "c" },
      { label: "$\\mathbb{N}$", value: "d" },
    ],
    correctOption: "b",
    solution: "$\\{1, 2\\} \\subset A$, da alle Elemente auch in $A$ enthalten sind.",
  },
  {
    id: "gr-mengen-2",
    lessonId: "m-grundlagen-mengen",
    difficulty: 1,
    type: "input",
    question: "Wie viele Elemente hat $A = \\{2, 4, 6, 8\\}$?",
    expectedAnswer: "4",
    format: "Ganze Zahl",
    solution: "$|A| = 4$ (4 Elemente in der Menge).",
  },
  {
    id: "gr-mengen-3",
    lessonId: "m-grundlagen-mengen",
    difficulty: 2,
    type: "input",
    question: "Gegeben $A = \\{1, 2, 3, 4\\}$ und $B = \\{3, 4, 5, 6\\}$. Berechne $|A \\cup B|$.",
    expectedAnswer: "6",
    format: "Ganze Zahl",
    solution: "$A \\cup B = \\{1, 2, 3, 4, 5, 6\\}$, also $|A \\cup B| = 6$.",
  },
  {
    id: "gr-mengen-4",
    lessonId: "m-grundlagen-mengen",
    difficulty: 2,
    type: "input",
    question: "Gegeben $A = \\{1, 2, 3, 4\\}$ und $B = \\{3, 4, 5, 6\\}$. Berechne $|A \\cap B|$.",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "$A \\cap B = \\{3, 4\\}$, also $|A \\cap B| = 2$.",
  },
  {
    id: "gr-mengen-5",
    lessonId: "m-grundlagen-mengen",
    difficulty: 3,
    type: "input",
    question: "Gegeben $A = \\{1, 2, 3\\}$, $B = \\{2, 3, 4\\}$, $C = \\{3, 4, 5\\}$. Berechne $|(A \\cup B) \\cap C|$.",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "$A \\cup B = \\{1, 2, 3, 4\\}$. Dann $(A \\cup B) \\cap C = \\{3, 4\\}$, also 2.",
  },
  {
    id: "gr-mengen-6",
    lessonId: "m-grundlagen-mengen",
    difficulty: 3,
    type: "multiple",
    question: "Was ist $A \\setminus B$ wenn $A = \\{1, 2, 3, 4\\}$ und $B = \\{3, 4, 5\\}$?",
    options: [
      { label: "$\\{1, 2\\}$", value: "a" },
      { label: "$\\{5\\}$", value: "b" },
      { label: "$\\{1, 2, 5\\}$", value: "c" },
      { label: "$\\{3, 4\\}$", value: "d" },
    ],
    correctOption: "a",
    solution: "$A \\setminus B$ enthält Elemente in $A$ aber nicht in $B$: $\\{1, 2\\}$.",
  },

  // mg2: Logische Aussagen
  {
    id: "gr-logik-1",
    lessonId: "m-grundlagen-mengen",
    difficulty: 1,
    type: "multiple",
    question: "Was bedeutet $P \\land Q$?",
    options: [
      { label: "P oder Q", value: "a" },
      { label: "P und Q", value: "b" },
      { label: "Nicht P", value: "c" },
      { label: "P impliziert Q", value: "d" },
    ],
    correctOption: "b",
    solution: "$P \\land Q$ bedeutet \"P und Q\" - beide Aussagen müssen wahr sein.",
  },
  {
    id: "gr-logik-2",
    lessonId: "m-grundlagen-mengen",
    difficulty: 2,
    type: "multiple",
    question: "Wann ist $P \\rightarrow Q$ falsch?",
    options: [
      { label: "P wahr, Q wahr", value: "a" },
      { label: "P wahr, Q falsch", value: "b" },
      { label: "P falsch, Q wahr", value: "c" },
      { label: "P falsch, Q falsch", value: "d" },
    ],
    correctOption: "b",
    solution: "$P \\rightarrow Q$ ist nur falsch wenn P wahr und Q falsch ist.",
  },
  {
    id: "gr-logik-3",
    lessonId: "m-grundlagen-mengen",
    difficulty: 3,
    type: "multiple",
    question: "Was ist die Negation von $\\forall x: P(x)$?",
    options: [
      { label: "$\\forall x: \\neg P(x)$", value: "a" },
      { label: "$\\exists x: \\neg P(x)$", value: "b" },
      { label: "$\\exists x: P(x)$", value: "c" },
      { label: "$\\neg P(x)$", value: "d" },
    ],
    correctOption: "b",
    solution: "$\\neg(\\forall x: P(x)) \\equiv \\exists x: \\neg P(x)$ - De Morgan für Quantoren.",
  },

  // ===== m-grundlagen-funktionen (mf1, mf2, mf3) =====
  {
    id: "gr-func-1",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 1,
    type: "input",
    question: "Gegeben $f(x) = 2x + 3$. Berechne $f(4)$.",
    expectedAnswer: "11",
    format: "Ganze Zahl",
    solution: "$f(4) = 2 \\cdot 4 + 3 = 11$.",
  },
  {
    id: "gr-func-2",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 1,
    type: "input",
    question: "Gegeben $f(x) = x^2$. Berechne $f(3)$.",
    expectedAnswer: "9",
    format: "Ganze Zahl",
    solution: "$f(3) = 3^2 = 9$.",
  },
  {
    id: "gr-func-3",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 2,
    type: "multiple",
    question: "Was ist der Definitionsbereich von $f(x) = \\frac{1}{x-2}$?",
    options: [
      { label: "$\\mathbb{R}$", value: "a" },
      { label: "$\\mathbb{R} \\setminus \\{2\\}$", value: "b" },
      { label: "$\\mathbb{R} \\setminus \\{-2\\}$", value: "c" },
      { label: "$[2, \\infty)$", value: "d" },
    ],
    correctOption: "b",
    solution: "Nenner $\\neq 0$: $x - 2 \\neq 0 \\Rightarrow x \\neq 2$.",
  },
  {
    id: "gr-func-4",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 2,
    type: "multiple",
    question: "Welche Funktion ist gerade (achsensymmetrisch)?",
    options: [
      { label: "$f(x) = x + 1$", value: "a" },
      { label: "$f(x) = x^2$", value: "b" },
      { label: "$f(x) = x^3$", value: "c" },
      { label: "$f(x) = x + x^2$", value: "d" },
    ],
    correctOption: "b",
    solution: "Gerade: $f(-x) = f(x)$. Für $x^2$: $(-x)^2 = x^2$ ✅",
  },
  {
    id: "gr-func-5",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 3,
    type: "input",
    question: "Gegeben $f(x) = x^2 - 4x + 3$. Berechne $f(a+1)$ als Term in $a$ (ohne Leerzeichen).",
    expectedAnswer: "a^2-2a",
    format: "Term wie a^2-2a",
    solution: "$f(a+1) = (a+1)^2 - 4(a+1) + 3 = a^2 + 2a + 1 - 4a - 4 + 3 = a^2 - 2a$.",
  },
  {
    id: "gr-func-6",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 3,
    type: "input",
    question: "Gegeben $f(x) = 3x - 1$. Finde $f^{-1}(5)$.",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "$y = 3x - 1 \\Rightarrow 5 = 3x - 1 \\Rightarrow x = 2$.",
  },
];

// ==================== MATHE 1 ====================

export const mathe1Exercises: Exercise[] = [
  // ===== m1-grenzwerte =====
  {
    id: "m1-gw-1",
    lessonId: "m1-grenzwerte",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\lim_{x \\to 3} (2x + 1)$.",
    expectedAnswer: "7",
    format: "Ganze Zahl",
    solution: "Einsetzen: $2 \\cdot 3 + 1 = 7$.",
  },
  {
    id: "m1-gw-2",
    lessonId: "m1-grenzwerte",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\lim_{x \\to 2} (x^2 + 1)$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "Einsetzen: $2^2 + 1 = 5$.",
  },
  {
    id: "m1-gw-3",
    lessonId: "m1-grenzwerte",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}$.",
    expectedAnswer: "4",
    format: "Ganze Zahl",
    solution: "$\\frac{(x-2)(x+2)}{x-2} = x+2$ für $x \\neq 2$. Also $2+2 = 4$.",
  },
  {
    id: "m1-gw-4",
    lessonId: "m1-grenzwerte",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\lim_{x \\to 0} \\frac{\\sin x}{x}$.",
    expectedAnswer: "1",
    format: "Ganze Zahl",
    solution: "Standardgrenzwert: $\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$.",
  },
  {
    id: "m1-gw-5",
    lessonId: "m1-grenzwerte",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\lim_{x \\to \\infty} \\frac{3x^2 + x}{2x^2 - 1}$. Gib eine Dezimalzahl auf 2 Stellen.",
    expectedAnswer: "1.50",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.50",
    solution: "Koeffizienten der höchsten Potenz: $\\frac{3}{2} = 1.5$.",
  },
  {
    id: "m1-gw-6",
    lessonId: "m1-grenzwerte",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\lim_{x \\to 0} \\frac{e^x - 1}{x}$. Dezimalzahl auf 2 Stellen.",
    expectedAnswer: "1.00",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.00",
    solution: "Standardgrenzwert: $\\lim_{x \\to 0} \\frac{e^x - 1}{x} = 1$.",
  },

  // ===== m1-ableitungen =====
  {
    id: "m1-diff-1",
    lessonId: "m1-ableitungen",
    difficulty: 1,
    type: "input",
    question: "Berechne die 1. Ableitung von $f(x) = x^3$. Gib den Term an.",
    expectedAnswer: "3x^2",
    format: "Term wie 3x^2",
    solution: "$f'(x) = 3x^2$ (Potenzregel).",
  },
  {
    id: "m1-diff-2",
    lessonId: "m1-ableitungen",
    difficulty: 1,
    type: "input",
    question: "Berechne $f'(x)$ für $f(x) = x^4$.",
    expectedAnswer: "4x^3",
    format: "Term wie 4x^3",
    solution: "$f'(x) = 4x^3$ (Potenzregel).",
  },
  {
    id: "m1-diff-3",
    lessonId: "m1-ableitungen",
    difficulty: 2,
    type: "input",
    question: "Berechne $f'(x)$ für $f(x) = (2x + 1)^3$. Gib den vereinfachten Term an.",
    expectedAnswer: "6(2x+1)^2",
    format: "Term wie 6(2x+1)^2",
    solution: "Kettenregel: $f'(x) = 3(2x+1)^2 \\cdot 2 = 6(2x+1)^2$.",
  },
  {
    id: "m1-diff-4",
    lessonId: "m1-ableitungen",
    difficulty: 2,
    type: "multiple",
    question: "Was ist die Ableitung von $f(x) = \\sin(x)$?",
    options: [
      { label: "$\\cos(x)$", value: "a" },
      { label: "$-\\sin(x)$", value: "b" },
      { label: "$-\\cos(x)$", value: "c" },
      { label: "$\\tan(x)$", value: "d" },
    ],
    correctOption: "a",
    solution: "$f'(x) = \\cos(x)$ - Grundableitung.",
  },
  {
    id: "m1-diff-5",
    lessonId: "m1-ableitungen",
    difficulty: 3,
    type: "input",
    question: "Berechne $f'(x)$ für $f(x) = x^2 \\cdot e^x$. Gib den Term an.",
    expectedAnswer: "xe^x(x+2)",
    format: "Faktorisierte Form",
    solution: "Produktregel: $f'(x) = 2x \\cdot e^x + x^2 \\cdot e^x = xe^x(x+2)$.",
  },
  {
    id: "m1-diff-6",
    lessonId: "m1-ableitungen",
    difficulty: 3,
    type: "input",
    question: "Berechne die 2. Ableitung von $f(x) = x^3 - 2x^2 + x$.",
    expectedAnswer: "6x-4",
    format: "Term wie 6x-4",
    solution: "$f'(x) = 3x^2 - 4x + 1$, $f''(x) = 6x - 4$.",
  },

  // ===== m1-integration =====
  {
    id: "m1-int-1",
    lessonId: "m1-integration",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\int 2x \\, dx$. Gib den Term an (+C nicht nötig).",
    expectedAnswer: "x^2",
    format: "Term wie x^2",
    solution: "$\\int 2x \\, dx = x^2 + C$ (Potenzregel umgekehrt).",
  },
  {
    id: "m1-int-2",
    lessonId: "m1-integration",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\int x^2 \\, dx$. Gib den Term an.",
    expectedAnswer: "x^3/3",
    format: "Term wie x^3/3",
    solution: "$\\int x^2 \\, dx = \\frac{x^3}{3} + C$.",
  },
  {
    id: "m1-int-3",
    lessonId: "m1-integration",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\int_0^2 x^2 \\, dx$. Gib eine Dezimalzahl auf 2 Stellen.",
    expectedAnswer: "2.67",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 2.67",
    solution: "$\\left[\\frac{x^3}{3}\\right]_0^2 = \\frac{8}{3} \\approx 2.67$.",
  },
  {
    id: "m1-int-4",
    lessonId: "m1-integration",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\int_1^3 2x \\, dx$.",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "$\\left[x^2\\right]_1^3 = 9 - 1 = 8$.",
  },
  {
    id: "m1-int-5",
    lessonId: "m1-integration",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\int_0^1 (3x^2 + 2x) \\, dx$.",
    expectedAnswer: "2",
    format: "Ganze Zahl oder Dezimal",
    solution: "$\\left[x^3 + x^2\\right]_0^1 = (1 + 1) - 0 = 2$.",
  },
  {
    id: "m1-int-6",
    lessonId: "m1-integration",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\int e^{2x} \\, dx$. Gib den Term an.",
    expectedAnswer: "e^{2x}/2",
    format: "Term wie e^{2x}/2",
    solution: "$\\int e^{2x} \\, dx = \\frac{e^{2x}}{2} + C$ (Substitution $u = 2x$).",
  },

  // ===== m1-reihen =====
  {
    id: "m1-reihe-1",
    lessonId: "m1-reihen",
    difficulty: 1,
    type: "input",
    question: "Summe der ersten 5 Glieder: $a_n = 2n$ für $n = 1$ bis $5$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$2 + 4 + 6 + 8 + 10 = 30$.",
  },
  {
    id: "m1-reihe-2",
    lessonId: "m1-reihen",
    difficulty: 1,
    type: "input",
    question: "Summe: $\\sum_{n=1}^{4} n^2$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$1 + 4 + 9 + 16 = 30$.",
  },
  {
    id: "m1-reihe-3",
    lessonId: "m1-reihen",
    difficulty: 2,
    type: "multiple",
    question: "Welche Reihe konvergiert?",
    options: [
      { label: "$\\sum_{n=1}^{\\infty} n$", value: "a" },
      { label: "$\\sum_{n=1}^{\\infty} \\frac{1}{n}$", value: "b" },
      { label: "$\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$", value: "c" },
      { label: "$\\sum_{n=1}^{\\infty} 2^n$", value: "d" },
    ],
    correctOption: "c",
    solution: "$\\sum \\frac{1}{n^2}$ konvergiert (p-Reihe mit $p = 2 > 1$).",
  },
  {
    id: "m1-reihe-4",
    lessonId: "m1-reihen",
    difficulty: 2,
    type: "input",
    question: "Summe der geometrischen Reihe: $a_1 = 2$, $q = 0.5$. Gib die Grenze an.",
    expectedAnswer: "4",
    format: "Ganze oder Dezimalzahl",
    solution: "$S = \\frac{a_1}{1-q} = \\frac{2}{0.5} = 4$.",
  },
  {
    id: "m1-reihe-5",
    lessonId: "m1-reihen",
    difficulty: 3,
    type: "input",
    question: "Grenzwert der geometrischen Reihe $\\sum_{n=0}^{\\infty} (\\frac{1}{3})^n$. Dezimal auf 2 Stellen.",
    expectedAnswer: "1.50",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.50",
    solution: "$S = \\frac{a}{1-q} = \\frac{1}{1 - 1/3} = \\frac{3}{2} = 1.5$.",
  },
  {
    id: "m1-reihe-6",
    lessonId: "m1-reihen",
    difficulty: 3,
    type: "multiple",
    question: "Welches Konvergenzkriterium ist korrekt für $\\sum \\frac{1}{n^2}$?",
    options: [
      { label: "Quotientenkriterium: $q = 1$", value: "a" },
      { label: "p-Reihe mit $p = 2 > 1$", value: "b" },
      { label: "Leibniz-Kriterium", value: "c" },
      { label: "Divergenz durch $a_n \\to 0$", value: "d" },
    ],
    correctOption: "b",
    solution: "$\\sum \\frac{1}{n^p}$ konvergiert für $p > 1$. Hier $p = 2$.",
  },
];

// ==================== MATHE 2 ====================

export const mathe2Exercises: Exercise[] = [
  // ===== m2-vektoren =====
  {
    id: "m2-vec-1",
    lessonId: "m2-vektoren",
    difficulty: 1,
    type: "input",
    question: "$\\vec{a} = \\binom{2}{3}$, $\\vec{b} = \\binom{1}{4}$. Berechne $\\vec{a} + \\vec{b}$ (erster Eintrag).",
    expectedAnswer: "3",
    format: "Ganze Zahl",
    solution: "$\\vec{a} + \\vec{b} = \\binom{2+1}{3+4} = \\binom{3}{7}$. Erster Eintrag: 3.",
  },
  {
    id: "m2-vec-2",
    lessonId: "m2-vektoren",
    difficulty: 1,
    type: "input",
    question: "$\\vec{a} = \\binom{3}{4}$. Berechne $|\\vec{a}|$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "$|\\vec{a}| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = \\sqrt{25} = 5$.",
  },
  {
    id: "m2-vec-3",
    lessonId: "m2-vektoren",
    difficulty: 2,
    type: "input",
    question: "$\\vec{a} = \\binom{3}{1}$, $\\vec{b} = \\binom{2}{-5}$. Berechne $\\vec{a} \\cdot \\vec{b}$.",
    expectedAnswer: "1",
    format: "Ganze Zahl",
    solution: "$\\vec{a} \\cdot \\vec{b} = 3 \\cdot 2 + 1 \\cdot (-5) = 6 - 5 = 1$.",
  },
  {
    id: "m2-vec-4",
    lessonId: "m2-vektoren",
    difficulty: 2,
    type: "multiple",
    question: "Wann sind zwei Vektoren orthogonal?",
    options: [
      { label: "Wenn sie parallel sind", value: "a" },
      { label: "Wenn ihr Skalarprodukt = 0 ist", value: "b" },
      { label: "Wenn sie gleich lang sind", value: "c" },
      { label: "Wenn ihre Summe = 0 ist", value: "d" },
    ],
    correctOption: "b",
    solution: "Orthogonal: $\\vec{a} \\cdot \\vec{b} = 0$ (Winkel = 90°).",
  },
  {
    id: "m2-vec-5",
    lessonId: "m2-vektoren",
    difficulty: 3,
    type: "input",
    question: "$\\vec{a} = \\binom{1}{2}{3}$, $\\vec{b} = \\binom{4}{5}{6}$. Berechne $\\vec{a} \\cdot \\vec{b}$.",
    expectedAnswer: "32",
    format: "Ganze Zahl",
    solution: "$\\vec{a} \\cdot \\vec{b} = 1 \\cdot 4 + 2 \\cdot 5 + 3 \\cdot 6 = 4 + 10 + 18 = 32$.",
  },
  {
    id: "m2-vec-6",
    lessonId: "m2-vektoren",
    difficulty: 3,
    type: "input",
    question: "Betrag von $\\vec{a} = \\binom{1}{2}{3}$. Dezimal auf 2 Stellen.",
    expectedAnswer: "3.74",
    tolerance: 0.01,
    format: "Dezimal, z.B. 3.74",
    solution: "$|\\vec{a}| = \\sqrt{1 + 4 + 9} = \\sqrt{14} \\approx 3.74$.",
  },

  // ===== m2-dgl =====
  {
    id: "m2-dgl-1",
    lessonId: "m2-dgl",
    difficulty: 1,
    type: "multiple",
    question: "Welche Funktion ist Lösung von $y' = 2y$?",
    options: [
      { label: "$y = 2x$", value: "a" },
      { label: "$y = e^{2x}$", value: "b" },
      { label: "$y = x^2$", value: "c" },
      { label: "$y = 2^x$", value: "d" },
    ],
    correctOption: "b",
    solution: "$y = e^{2x}$ → $y' = 2e^{2x} = 2y$. ✅",
  },
  {
    id: "m2-dgl-2",
    lessonId: "m2-dgl",
    difficulty: 1,
    type: "multiple",
    question: "Was ist eine homogene lineare DGL 1. Ordnung?",
    options: [
      { label: "$y' + y = x$", value: "a" },
      { label: "$y' + y = 0$", value: "b" },
      { label: "$y' = y^2$", value: "c" },
      { label: "$y'' + y = 0$", value: "d" },
    ],
    correctOption: "b",
    solution: "Homogen: Rechte Seite = 0. $y' + y = 0$ ist homogen linear 1. Ordnung.",
  },
  {
    id: "m2-dgl-3",
    lessonId: "m2-dgl",
    difficulty: 2,
    type: "input",
    question: "Löse $y' = 3y$, $y(0) = 2$. Berechne $y(1)$ auf 2 Stellen.",
    expectedAnswer: "40.17",
    tolerance: 0.1,
    format: "Dezimalzahl, z.B. 40.17",
    solution: "$y = 2e^{3x}$. $y(1) = 2e^3 \\approx 40.17$.",
  },
  {
    id: "m2-dgl-4",
    lessonId: "m2-dgl",
    difficulty: 2,
    type: "multiple",
    question: "Was ist die allgemeine Lösung von $y' = ky$?",
    options: [
      { label: "$y = kx + C$", value: "a" },
      { label: "$y = Ce^{kx}$", value: "b" },
      { label: "$y = Ck^x$", value: "c" },
      { label: "$y = e^{kx} + C$", value: "d" },
    ],
    correctOption: "b",
    solution: "Lösung: $y = Ce^{kx}$ (Exponentialfunktion).",
  },
  {
    id: "m2-dgl-5",
    lessonId: "m2-dgl",
    difficulty: 3,
    type: "input",
    question: "Löse $y' = xy$, $y(0) = 1$. Gib $y(2)$ auf 2 Stellen an.",
    expectedAnswer: "7.39",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 7.39",
    solution: "$y = e^{x^2/2}$. $y(2) = e^2 \\approx 7.39$.",
  },
  {
    id: "m2-dgl-6",
    lessonId: "m2-dgl",
    difficulty: 3,
    type: "input",
    question: "Löse $y'' - 3y' + 2y = 0$. Gib die charakteristische Gleichung als Term an (z.B. r^2-3r+2=0).",
    expectedAnswer: "r^2-3r+2=0",
    format: "Gleichung wie r^2-3r+2=0",
    solution: "Charakteristisch: $r^2 - 3r + 2 = 0$ → $(r-1)(r-2) = 0$ → $r_1 = 1, r_2 = 2$.",
  },
];

// ==================== GEOMETRIE ====================

export const geometrieExercises: Exercise[] = [
  {
    id: "geo-1",
    lessonId: "m-geometrie-flaechen",
    difficulty: 1,
    type: "input",
    question: "Berechne die Fläche eines Rechtecks mit $a = 7\\text{cm}$ und $b = 3\\text{cm}$.",
    expectedAnswer: "21",
    format: "Ganze Zahl",
    solution: "$A = a \\cdot b = 7 \\cdot 3 = 21\\text{cm}^2$.",
  },
  {
    id: "geo-2",
    lessonId: "m-geometrie-flaechen",
    difficulty: 1,
    type: "input",
    question: "Berechne die Fläche eines Dreiecks mit Grundseite $g = 10$ und Höhe $h = 6$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$A = \\frac{g \\cdot h}{2} = \\frac{10 \\cdot 6}{2} = 30$.",
  },
  {
    id: "geo-3",
    lessonId: "m-geometrie-flaechen",
    difficulty: 2,
    type: "input",
    question: "Berechne die Fläche eines Kreises mit Radius $r = 4$. Gib den Faktor vor $\\pi$ an.",
    expectedAnswer: "16",
    format: "Ganze Zahl",
    solution: "$A = \\pi r^2 = 16\\pi$. Der Faktor ist 16.",
  },
  {
    id: "geo-4",
    lessonId: "m-geometrie-flaechen",
    difficulty: 2,
    type: "input",
    question: "Berechne das Volumen eines Quaders mit $a=3$, $b=4$, $c=5$.",
    expectedAnswer: "60",
    format: "Ganze Zahl",
    solution: "$V = a \\cdot b \\cdot c = 3 \\cdot 4 \\cdot 5 = 60$.",
  },
  {
    id: "geo-5",
    lessonId: "m-geometrie-flaechen",
    difficulty: 3,
    type: "input",
    question: "Im rechtwinkligen Dreieck: $a = 8$, $b = 15$. Berechne die Hypotenuse $c$.",
    expectedAnswer: "17",
    format: "Ganze Zahl",
    solution: "Pythagoras: $c = \\sqrt{8^2 + 15^2} = \\sqrt{64 + 225} = \\sqrt{289} = 17$.",
  },
  {
    id: "geo-6",
    lessonId: "m-geometrie-flaechen",
    difficulty: 3,
    type: "input",
    question: "Berechne das Volumen einer Kugel mit $r = 3$. Gib den Faktor vor $\\pi$ an.",
    expectedAnswer: "36",
    format: "Ganze Zahl",
    solution: "$V = \\frac{4}{3}\\pi r^3 = \\frac{4}{3}\\pi \\cdot 27 = 36\\pi$. Der Faktor ist 36.",
  },
];

// ==================== TRIGONOMETRIE ====================

export const trigonometrieExercises: Exercise[] = [
  {
    id: "trig-1",
    lessonId: "m-trigonometrie",
    difficulty: 1,
    type: "input",
    question: "Was ist $\\sin(90°)$?",
    expectedAnswer: "1",
    format: "Ganze Zahl oder Dezimal",
    solution: "$\\sin(90°) = 1$.",
  },
  {
    id: "trig-2",
    lessonId: "m-trigonometrie",
    difficulty: 1,
    type: "input",
    question: "Im rechtwinkligen Dreieck: Gegenkathete $= 3$, Hypotenuse $= 5$. Berechne $\\sin(\\alpha)$ als Bruch (z.B. 3/5).",
    expectedAnswer: "3/5",
    format: "Bruch wie 3/5",
    solution: "$\\sin(\\alpha) = \\frac{3}{5}$.",
  },
  {
    id: "trig-3",
    lessonId: "m-trigonometrie",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\cos(60°)$ als Bruch (z.B. 1/2).",
    expectedAnswer: "1/2",
    format: "Bruch wie 1/2",
    solution: "$\\cos(60°) = \\frac{1}{2}$.",
  },
  {
    id: "trig-4",
    lessonId: "m-trigonometrie",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\tan(45°)$.",
    expectedAnswer: "1",
    format: "Ganze Zahl",
    solution: "$\\tan(45°) = \\frac{\\sin(45°)}{\\cos(45°)} = 1$.",
  },
  {
    id: "trig-5",
    lessonId: "m-trigonometrie",
    difficulty: 3,
    type: "input",
    question: "Gegeben: $a = 5$, $b = 7$, $\\gamma = 60°$. Berechne $c^2$ (Satz des Kosinus).",
    expectedAnswer: "39",
    format: "Ganze Zahl",
    solution: "$c^2 = a^2 + b^2 - 2ab\\cos(\\gamma) = 25 + 49 - 70 \\cdot 0.5 = 74 - 35 = 39$.",
  },
  {
    id: "trig-6",
    lessonId: "m-trigonometrie",
    difficulty: 3,
    type: "input",
    question: "Im rechtwinkligen Dreieck: $a = 6$, $c = 10$. Berechne $\\cos(\\alpha)$ als Dezimalzahl.",
    expectedAnswer: "0.8",
    format: "Dezimalzahl",
    solution: "$b = \\sqrt{100 - 36} = 8$. $\\cos(\\alpha) = \\frac{b}{c} = \\frac{8}{10} = 0.8$.",
  },
];

// ==================== POTENZEN ====================

export const potenzenExercises: Exercise[] = [
  {
    id: "pot-1",
    lessonId: "m-potenzen-log",
    difficulty: 1,
    type: "input",
    question: "Berechne $2^5$.",
    expectedAnswer: "32",
    format: "Ganze Zahl",
    solution: "$2^5 = 2 \\cdot 2 \\cdot 2 \\cdot 2 \\cdot 2 = 32$.",
  },
  {
    id: "pot-2",
    lessonId: "m-potenzen-log",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\log_{10}(1000)$.",
    expectedAnswer: "3",
    format: "Ganze Zahl",
    solution: "$10^3 = 1000$, also $\\log_{10}(1000) = 3$.",
  },
  {
    id: "pot-3",
    lessonId: "m-potenzen-log",
    difficulty: 2,
    type: "input",
    question: "Vereinfache $\\frac{2^8}{2^5}$.",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "$\\frac{2^8}{2^5} = 2^{8-5} = 2^3 = 8$.",
  },
  {
    id: "pot-4",
    lessonId: "m-potenzen-log",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\sqrt{144}$.",
    expectedAnswer: "12",
    format: "Ganze Zahl",
    solution: "$\\sqrt{144} = 12$, da $12^2 = 144$.",
  },
  {
    id: "pot-5",
    lessonId: "m-potenzen-log",
    difficulty: 3,
    type: "input",
    question: "Löse: $3^x = 81$.",
    expectedAnswer: "4",
    format: "Ganze Zahl",
    solution: "$81 = 3^4$, also $x = 4$.",
  },
  {
    id: "pot-6",
    lessonId: "m-potenzen-log",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\ln(e^5)$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "$\\ln(e^5) = 5$ (ln und $e^x$ sind Umkehrfunktionen).",
  },
];

// ==================== STATISTIK ====================

export const statistikExercises: Exercise[] = [
  {
    id: "stat-1",
    lessonId: "m-statistik",
    difficulty: 1,
    type: "input",
    question: "Berechne den Mittelwert von $4, 8, 12$.",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "$\\bar{x} = \\frac{4+8+12}{3} = \\frac{24}{3} = 8$.",
  },
  {
    id: "stat-2",
    lessonId: "m-statistik",
    difficulty: 1,
    type: "input",
    question: "Was ist der Median von $2, 5, 9$?",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "Sortiert: $2, 5, 9$. Der mittlere Wert ist 5.",
  },
  {
    id: "stat-3",
    lessonId: "m-statistik",
    difficulty: 2,
    type: "input",
    question: "Berechne den Mittelwert von $10, 20, 30, 40, 50$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$\\bar{x} = \\frac{10+20+30+40+50}{5} = \\frac{150}{5} = 30$.",
  },
  {
    id: "stat-4",
    lessonId: "m-statistik",
    difficulty: 2,
    type: "input",
    question: "Daten: $2, 4, 6$. Berechne die Varianz $s^2$.",
    expectedAnswer: "2.67",
    tolerance: 0.01,
    format: "Dezimalzahl",
    solution: "$\\bar{x} = 4$. $s^2 = \\frac{(2-4)^2+(4-4)^2+(6-4)^2}{3} = \\frac{4+0+4}{3} = \\frac{8}{3} \\approx 2.67$.",
  },
  {
    id: "stat-5",
    lessonId: "m-statistik",
    difficulty: 3,
    type: "input",
    question: "Daten: $1, 2, 3, 4, 5$. Berechne die Standardabweichung $s$ auf 2 Stellen.",
    expectedAnswer: "1.41",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.41",
    solution: "$\\bar{x} = 3$. $s^2 = \\frac{4+1+0+1+4}{5} = 2$. $s = \\sqrt{2} \\approx 1.41$.",
  },
  {
    id: "stat-6",
    lessonId: "m-statistik",
    difficulty: 3,
    type: "input",
    question: "Daten: $3, 5, 7, 9, 11, 13$. Was ist der Median?",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "Gerade Anzahl: Median = $\\frac{7+9}{2} = 8$.",
  },
];

// Alle zusammen

// ==================== STOCHASTIK ====================

export const stochastikExercises: Exercise[] = [
  {
    id: "sto-1",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Ein fairer Würfel wird geworfen. Wie groß ist $P(\\text{gerade Zahl})$? Gib den Bruch an (z.B. 1/2).",
    expectedAnswer: "1/2",
    format: "Bruch wie 1/2",
    solution: "Gerade Zahlen: {2, 4, 6} = 3 von 6. Also $P = 3/6 = 1/2$.",
  },
  {
    id: "sto-2",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Aus einem Kartenspiel (52 Karten) wird eine gezogen. Wie groß ist $P(\\text{Herz})$? Gib den Bruch an.",
    expectedAnswer: "1/4",
    format: "Bruch wie 1/4",
    solution: "Herz: 13 von 52 Karten. $P = 13/52 = 1/4$.",
  },
  {
    id: "sto-3",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "$P(A) = 0.6$, $P(B) = 0.4$, $P(A \\cap B) = 0.2$. Berechne $P(A \\cup B)$.",
    expectedAnswer: "0.8",
    format: "Dezimalzahl",
    solution: "Additionssatz: $P(A \\cup B) = 0.6 + 0.4 - 0.2 = 0.8$.",
  },
  {
    id: "sto-4",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "Wie viele 3-stellige Zahlen kann man aus {1,2,3,4,5} bilden ohne Wiederholung?",
    expectedAnswer: "60",
    format: "Ganze Zahl",
    solution: "Variation ohne Zurücklegen: $V_3^5 = 5 \\cdot 4 \\cdot 3 = 60$.",
  },
  {
    id: "sto-5",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "In einer Urne sind 6 rote und 4 blaue Kugeln. Zwei werden gezogen (ohne Zurücklegen). Wie groß ist $P(\\text{beide rot})$? Gib den Bruch an.",
    expectedAnswer: "1/3",
    format: "Bruch wie 1/3",
    solution: "$P = \\frac{6}{10} \\cdot \\frac{5}{9} = \\frac{30}{90} = \\frac{1}{3}$.",
  },
  {
    id: "sto-6",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "Wie viele Kombinationen von 5 aus 10 Objekten gibt es? $\\binom{10}{5}$?",
    expectedAnswer: "252",
    format: "Ganze Zahl",
    solution: "$\\binom{10}{5} = \\frac{10!}{5! \\cdot 5!} = 252$.",
  },
];

// ==================== KOMPLEXE ZAHLEN ====================

export const komplexeExercises: Exercise[] = [
  {
    id: "kz-1",
    lessonId: "m-komplexe-zahlen",
    difficulty: 1,
    type: "input",
    question: "Berechne $(3 + 2i) + (1 - 4i)$. Gib im Format a+bi an (z.B. 4-2i).",
    expectedAnswer: "4-2i",
    format: "Format: a+bi",
    solution: "$(3+1) + (2-4)i = 4 - 2i$.",
  },
  {
    id: "kz-2",
    lessonId: "m-komplexe-zahlen",
    difficulty: 1,
    type: "input",
    question: "Was ist der Realteil von $z = -3 + 5i$?",
    expectedAnswer: "-3",
    format: "Ganze Zahl",
    solution: "Re(z) = -3.",
  },
  {
    id: "kz-3",
    lessonId: "m-komplexe-zahlen",
    difficulty: 2,
    type: "input",
    question: "Berechne $(2 + i)(3 - i)$. Gib im Format a+bi an.",
    expectedAnswer: "7+i",
    format: "Format: a+bi",
    solution: "$(2+i)(3-i) = 6 - 2i + 3i - i^2 = 6 + i + 1 = 7 + i$.",
  },
  {
    id: "kz-4",
    lessonId: "m-komplexe-zahlen",
    difficulty: 2,
    type: "input",
    question: "Berechne den Betrag von $z = 3 + 4i$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "$|z| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = \\sqrt{25} = 5$.",
  },
  {
    id: "kz-5",
    lessonId: "m-komplexe-zahlen",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\frac{2+i}{1-i}$. Gib im Format a+bi an.",
    expectedAnswer: "0.5+1.5i",
    format: "Format wie 0.5+1.5i",
    solution: "$\\frac{(2+i)(1+i)}{(1-i)(1+i)} = \\frac{2+2i+i+i^2}{2} = \\frac{1+3i}{2} = 0.5 + 1.5i$.",
  },
  {
    id: "kz-6",
    lessonId: "m-komplexe-zahlen",
    difficulty: 3,
    type: "input",
    question: "Gib $z = 1 + \\sqrt{3}i$ in Polardarstellung an (Betrag, Winkel in Grad).",
    expectedAnswer: "2,60",
    tolerance: 1,
    format: "Betrag,Winkel (z.B. 2,60)",
    solution: "$r = \\sqrt{1+3} = 2$, $\\varphi = \\arctan(\\sqrt{3}) = 60°$. Also $z = 2e^{i60°}$.",
  },
];

// ==================== NUMERIK ====================

export const numerikExercises: Exercise[] = [
  {
    id: "num-1",
    lessonId: "m-numerik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Berechne den absoluten Fehler für $x_{exakt} = 5$, $x_{approx} = 4.98$.",
    expectedAnswer: "0.02",
    format: "Dezimalzahl",
    solution: "$|5 - 4.98| = 0.02$.",
  },
  {
    id: "num-2",
    lessonId: "m-numerik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Berechne den relativen Fehler in % für $x_{exakt} = 100$, $x_{approx} = 98$.",
    expectedAnswer: "2",
    format: "Dezimalzahl",
    solution: "$\\frac{|100-98|}{100} = 0.02 = 2\\%$.",
  },
  {
    id: "num-3",
    lessonId: "m-numerik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "Bisektion: $f(x) = x^2 - 4$ auf [1,3]. Nach 3 Schritten: Was ist die neue obere Grenze b?",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "Schritt 1: m=2, f(2)=0 → fertig! Oder: $b=2$ wenn $f(a)\\cdot f(m) < 0$.",
  },
  {
    id: "num-4",
    lessonId: "m-numerik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "Newton: $f(x) = x^2 - 9$, $x_0 = 4$. Berechne $x_1$.",
    expectedAnswer: "4.125",
    tolerance: 0.01,
    format: "Dezimalzahl",
    solution: "$f'(x) = 2x$. $x_1 = 4 - \\frac{16-9}{8} = 4 - 0.875 = 3.125$.",
  },
  {
    id: "num-5",
    lessonId: "m-numerik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "Newton: $f(x) = x^3 - 5$, $x_0 = 2$. Berechne $x_1$ auf 3 Stellen.",
    expectedAnswer: "2.083",
    tolerance: 0.01,
    format: "Dezimalzahl",
    solution: "$f'(x) = 3x^2$. $x_1 = 2 - \\frac{8-5}{12} = 2 - 0.25 = 1.75$.",
  },
  {
    id: "num-6",
    lessonId: "m-numerik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "Wie viele Bisektionsschritte braucht man für Genauigkeit $10^{-6}$ auf [0,10]?",
    expectedAnswer: "24",
    format: "Ganze Zahl",
    solution: "$\\frac{10}{2^n} < 10^{-6}$ → $2^n > 10^7$ → $n > \\log_2(10^7) \\approx 23.25$ → $n = 24$.",
  },
];

// ==================== NEUE MATHE-GRUNDLAGEN ====================

export const bruchrechnenExercises: Exercise[] = [
  {
    id: "br-1", lessonId: "m-bruchrechnen", difficulty: 1, type: "input",
    question: "$\\frac{1}{2} + \\frac{1}{3} = ?$",
    expectedAnswer: "$\\frac{5}{6}$", format: "Bruch",
    solution: "$\\frac{1}{2} + \\frac{1}{3} = \\frac{3}{6} + \\frac{2}{6} = \\frac{5}{6}$",
  },
  {
    id: "br-2", lessonId: "m-bruchrechnen", difficulty: 1, type: "input",
    question: "$\\frac{3}{4} - \\frac{1}{4} = ?$",
    expectedAnswer: "$\\frac{1}{2}$", format: "Bruch",
    solution: "$\\frac{3}{4} - \\frac{1}{4} = \\frac{2}{4} = \\frac{1}{2}$",
  },
  {
    id: "br-3", lessonId: "m-bruchrechnen", difficulty: 1, type: "input",
    question: "$\\frac{2}{5} \\cdot \\frac{3}{7} = ?$",
    expectedAnswer: "$\\frac{6}{35}$", format: "Bruch",
    solution: "$\\frac{2}{5} \\cdot \\frac{3}{7} = \\frac{6}{35}$",
  },
  {
    id: "br-4", lessonId: "m-bruchrechnen", difficulty: 2, type: "input",
    question: "$\\frac{3}{8} : \\frac{2}{3} = ?$",
    expectedAnswer: "$\\frac{9}{16}$", format: "Bruch",
    solution: "$\\frac{3}{8} : \\frac{2}{3} = \\frac{3}{8} \\cdot \\frac{3}{2} = \\frac{9}{16}$",
  },
  {
    id: "br-5", lessonId: "m-bruchrechnen", difficulty: 2, type: "multiple",
    question: "Welcher Bruch ist am größten?",
    options: [
      { label: "$\\frac{2}{3}$", value: "a" },
      { label: "$\\frac{3}{5}$", value: "b" },
      { label: "$\\frac{7}{12}$", value: "c" },
      { label: "$\\frac{1}{2}$", value: "d" },
    ],
    correctOption: "a",
    solution: "$\\frac{2}{3} = 0{,}667$ ist am größten.",
  },
  {
    id: "br-6", lessonId: "m-bruchrechnen", difficulty: 2, type: "input",
    question: "$\\frac{1}{4} + \\frac{2}{3} + \\frac{1}{6} = ?$",
    expectedAnswer: "$\\frac{13}{12}$", format: "Bruch",
    solution: "$\\frac{3}{12} + \\frac{8}{12} + \\frac{2}{12} = \\frac{13}{12}$",
  },
];

export const gleichungenExercises: Exercise[] = [
  {
    id: "gl-1", lessonId: "m-gleichungen", difficulty: 1, type: "input",
    question: "Löse $2x + 6 = 14$",
    expectedAnswer: "4", format: "Ganze Zahl",
    solution: "$2x = 8 \\Rightarrow x = 4$",
  },
  {
    id: "gl-2", lessonId: "m-gleichungen", difficulty: 1, type: "input",
    question: "Löse $3x - 7 = 2$",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "$3x = 9 \\Rightarrow x = 3$",
  },
  {
    id: "gl-3", lessonId: "m-gleichungen", difficulty: 2, type: "input",
    question: "Löse $x^2 - 5x + 6 = 0$. Kleinere Lösung?",
    expectedAnswer: "2", format: "Ganze Zahl",
    solution: "$x^2 - 5x + 6 = (x-2)(x-3) = 0 \\Rightarrow x_1 = 2$",
  },
  {
    id: "gl-4", lessonId: "m-gleichungen", difficulty: 2, type: "input",
    question: "Löse $x^2 + 4x + 4 = 0$",
    expectedAnswer: "-2", format: "Ganze Zahl",
    solution: "$(x+2)^2 = 0 \\Rightarrow x = -2$",
  },
  {
    id: "gl-5", lessonId: "m-gleichungen", difficulty: 3, type: "multiple",
    question: "Wie viele reelle Lösungen hat $x^2 + 1 = 0$?",
    options: [
      { label: "0", value: "a" },
      { label: "1", value: "b" },
      { label: "2", value: "c" },
      { label: "3", value: "d" },
    ],
    correctOption: "a",
    solution: "$D = 0 - 4 = -4 < 0$ → keine reelle Lösung",
  },
  {
    id: "gl-6", lessonId: "m-gleichungen", difficulty: 2, type: "input",
    question: "Löse $5x - 3 = 2x + 9$",
    expectedAnswer: "4", format: "Ganze Zahl",
    solution: "$3x = 12 \\Rightarrow x = 4$",
  },
];

export const termumformungExercises: Exercise[] = [
  {
    id: "tu-1", lessonId: "m-termumformung", difficulty: 1, type: "input",
    question: "Löse $(x+3)^2$ aus.",
    expectedAnswer: "x^2 + 6x + 9", format: "Term",
    solution: "$(x+3)^2 = x^2 + 6x + 9$",
  },
  {
    id: "tu-2", lessonId: "m-termumformung", difficulty: 1, type: "input",
    question: "Löse $(x-5)(x+5)$ aus.",
    expectedAnswer: "x^2 - 25", format: "Term",
    solution: "$(x-5)(x+5) = x^2 - 25$",
  },
  {
    id: "tu-3", lessonId: "m-termumformung", difficulty: 2, type: "input",
    question: "Löse $(2x+1)^2$ aus.",
    expectedAnswer: "4x^2 + 4x + 1", format: "Term",
    solution: "$(2x+1)^2 = 4x^2 + 4x + 1$",
  },
  {
    id: "tu-4", lessonId: "m-termumformung", difficulty: 1, type: "multiple",
    question: "Was ist $(a+b)^2$?",
    options: [
      { label: "$a^2 + b^2$", value: "a" },
      { label: "$a^2 + 2ab + b^2$", value: "b" },
      { label: "$a^2 - 2ab + b^2$", value: "c" },
      { label: "$a^2 - b^2$", value: "d" },
    ],
    correctOption: "b",
    solution: "Binomische Formel: $(a+b)^2 = a^2 + 2ab + b^2$",
  },
  {
    id: "tu-5", lessonId: "m-termumformung", difficulty: 2, type: "input",
    question: "Faktorisiere $x^2 - 9$.",
    expectedAnswer: "(x+3)(x-3)", format: "Term",
    solution: "$x^2 - 9 = (x+3)(x-3)$",
  },
  {
    id: "tu-6", lessonId: "m-termumformung", difficulty: 2, type: "input",
    question: "Vereinfache $3(x+2) - 2(x-1)$.",
    expectedAnswer: "x + 8", format: "Term",
    solution: "$3x + 6 - 2x + 2 = x + 8$",
  },
];

export const ungleichungenExercises: Exercise[] = [
  {
    id: "ug-1", lessonId: "m-ungleichungen", difficulty: 1, type: "input",
    question: "Löse $2x + 3 > 7$",
    expectedAnswer: "x > 2", format: "Ungleichung",
    solution: "$2x > 4 \\Rightarrow x > 2$",
  },
  {
    id: "ug-2", lessonId: "m-ungleichungen", difficulty: 1, type: "input",
    question: "Löse $-3x \\leq 12$",
    expectedAnswer: "x \\geq -4", format: "Ungleichung",
    solution: "$-3x \\leq 12 \\Rightarrow x \\geq -4$ (Vorzeichenwechsel!)",
  },
  {
    id: "ug-3", lessonId: "m-ungleichungen", difficulty: 2, type: "multiple",
    question: "Für welche $x$ gilt $x^2 - 4 > 0$?",
    options: [
      { label: "$x > 2$", value: "a" },
      { label: "$x < -2$ oder $x > 2$", value: "b" },
      { label: "$-2 < x < 2$", value: "c" },
      { label: "$x > 0$", value: "d" },
    ],
    correctOption: "b",
    solution: "$(x-2)(x+2) > 0 \\Rightarrow x < -2$ oder $x > 2$",
  },
  {
    id: "ug-4", lessonId: "m-ungleichungen", difficulty: 2, type: "input",
    question: "Löse $5 - 2x < 1$",
    expectedAnswer: "x > 2", format: "Ungleichung",
    solution: "$-2x < -4 \\Rightarrow x > 2$",
  },
  {
    id: "ug-5", lessonId: "m-ungleichungen", difficulty: 3, type: "input",
    question: "Löse $|x - 3| < 5$",
    expectedAnswer: "-2 < x < 8", format: "Intervall",
    solution: "$-5 < x - 3 < 5 \\Rightarrow -2 < x < 8$",
  },
  {
    id: "ug-6", lessonId: "m-ungleichungen", difficulty: 2, type: "multiple",
    question: "Was bedeutet $(3, 7]$?",
    options: [
      { label: "$3 \\leq x < 7$", value: "a" },
      { label: "$3 < x \\leq 7$", value: "b" },
      { label: "$3 \\leq x \\leq 7$", value: "c" },
      { label: "$3 < x < 7$", value: "d" },
    ],
    correctOption: "b",
    solution: "$(3, 7]$ = $3 < x \\leq 7$ (offen links, geschlossen rechts)",
  },
];

export const kurvendiskussionExercises: Exercise[] = [
  {
    id: "kd-1", lessonId: "m-kurvendiskussion", difficulty: 1, type: "input",
    question: "$f(x) = 3x^2 + 2x - 1$. Bestimme $f\'(x)$.",
    expectedAnswer: "6x + 2", format: "Term",
    solution: "$f'(x) = 6x + 2$",
  },
  {
    id: "kd-2", lessonId: "m-kurvendiskussion", difficulty: 2, type: "input",
    question: "$f(x) = x^2 - 4x + 3$. Kleinere Nullstelle?",
    expectedAnswer: "1", format: "Ganze Zahl",
    solution: "$(x-1)(x-3) = 0 \\Rightarrow x_1 = 1$",
  },
  {
    id: "kd-3", lessonId: "m-kurvendiskussion", difficulty: 2, type: "input",
    question: "$f(x) = x^2 - 6x + 5$. Extremstelle bei x = ?",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "$f'(x) = 2x - 6 = 0 \\Rightarrow x = 3$ (Minimum)",
  },
  {
    id: "kd-4", lessonId: "m-kurvendiskussion", difficulty: 3, type: "multiple",
    question: "Hat $f(x) = x^3$ einen Wendepunkt?",
    options: [
      { label: "Ja, bei x=0", value: "a" },
      { label: "Nein", value: "b" },
      { label: "Ja, bei x=1", value: "c" },
      { label: "Ja, bei x=-1", value: "d" },
    ],
    correctOption: "a",
    solution: "$f''(x) = 6x = 0 \\Rightarrow x = 0$ → Wendepunkt bei $(0,0)$",
  },
  {
    id: "kd-5", lessonId: "m-kurvendiskussion", difficulty: 2, type: "input",
    question: "Wann steigt $f(x) = x^2 - 2x$?",
    expectedAnswer: "x > 1", format: "Ungleichung",
    solution: "$f'(x) = 2x - 2 > 0 \\Rightarrow x > 1$",
  },
  {
    id: "kd-6", lessonId: "m-kurvendiskussion", difficulty: 3, type: "input",
    question: "Wendepunkt von $f(x) = x^3 - 3x^2 + 2$?",
    expectedAnswer: "(1, 0)", format: "Punkt",
    solution: "$f''(x) = 6x - 6 = 0 \\Rightarrow x = 1$, $f(1) = 0$",
  },
];

export const gleichungssystemeExercises: Exercise[] = [
  {
    id: "lgs-1", lessonId: "m-lgs", difficulty: 1, type: "input",
    question: "$x + y = 5$, $x - y = 1$. x?",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "Addition: $2x = 6 \\Rightarrow x = 3$",
  },
  {
    id: "lgs-2", lessonId: "m-lgs", difficulty: 1, type: "input",
    question: "$x + y = 5$, $x - y = 1$. y?",
    expectedAnswer: "2", format: "Ganze Zahl",
    solution: "Subtraktion: $2y = 4 \\Rightarrow y = 2$",
  },
  {
    id: "lgs-3", lessonId: "m-lgs", difficulty: 2, type: "input",
    question: "$2x + y = 7$, $x - y = 2$. x?",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "Addition: $3x = 9 \\Rightarrow x = 3$",
  },
  {
    id: "lgs-4", lessonId: "m-lgs", difficulty: 2, type: "multiple",
    question: "Wie viele Lösungen hat $x + y = 1$, $2x + 2y = 3$?",
    options: [
      { label: "0", value: "a" },
      { label: "1", value: "b" },
      { label: "Unendlich", value: "c" },
      { label: "2", value: "d" },
    ],
    correctOption: "a",
    solution: "Parallel → keine Lösung",
  },
  {
    id: "lgs-5", lessonId: "m-lgs", difficulty: 3, type: "input",
    question: "$x + 2y = 5$, $3x - y = 1$. x?",
    expectedAnswer: "1", format: "Ganze Zahl",
    solution: "$y = 3x - 1 \\Rightarrow x + 6x - 2 = 5 \\Rightarrow x = 1$",
  },
  {
    id: "lgs-6", lessonId: "m-lgs", difficulty: 2, type: "input",
    question: "$3x + 2y = 12$, $x - y = 1$. y?",
    expectedAnswer: "$\\frac{9}{5}$", format: "Bruch",
    solution: "$5y = 9 \\Rightarrow y = \\frac{9}{5}$",
  },
];

export const matrizenExercises: Exercise[] = [
  {
    id: "ma-1", lessonId: "m-matrizen", difficulty: 1, type: "input",
    question: "$\det\begin{pmatrix}2&3\\1&4\end{pmatrix} = ?$",
    expectedAnswer: "5", format: "Ganze Zahl",
    solution: "$2 \\cdot 4 - 3 \\cdot 1 = 5$",
  },
  {
    id: "ma-2", lessonId: "m-matrizen", difficulty: 1, type: "input",
    question: "$\det\begin{pmatrix}1&2\\3&6\end{pmatrix} = ?$",
    expectedAnswer: "0", format: "Ganze Zahl",
    solution: "$1 \\cdot 6 - 2 \\cdot 3 = 0$",
  },
  {
    id: "ma-3", lessonId: "m-matrizen", difficulty: 2, type: "multiple",
    question: "Wann hat eine Matrix keine Inverse?",
    options: [
      { label: "Wenn det = 0", value: "a" },
      { label: "Wenn det = 1", value: "b" },
      { label: "Wenn sie quadratisch ist", value: "c" },
      { label: "Wenn sie symmetrisch ist", value: "d" },
    ],
    correctOption: "a",
    solution: "Nur invertierbar wenn $\det A \\neq 0$",
  },
  {
    id: "ma-4", lessonId: "m-matrizen", difficulty: 2, type: "input",
    question: "$\begin{pmatrix}1&2\\3&4\end{pmatrix} + \begin{pmatrix}5&6\\7&8\end{pmatrix}$. Element (1,1)?",
    expectedAnswer: "6", format: "Ganze Zahl",
    solution: "$1 + 5 = 6$",
  },
  {
    id: "ma-5", lessonId: "m-matrizen", difficulty: 3, type: "input",
    question: "$\begin{pmatrix}2&0\\0&3\end{pmatrix} \\cdot \begin{pmatrix}1&1\\1&1\end{pmatrix}$. Element (2,1)?",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "$0 \\cdot 1 + 3 \\cdot 1 = 3$",
  },
  {
    id: "ma-6", lessonId: "m-matrizen", difficulty: 2, type: "input",
    question: "$A = \begin{pmatrix}3&1\\2&4\end{pmatrix}$. det(A)?",
    expectedAnswer: "10", format: "Ganze Zahl",
    solution: "$3 \\cdot 4 - 1 \\cdot 2 = 10$",
  },
];

export const verteilungenExercises: Exercise[] = [
  {
    id: "vt-1", lessonId: "m-verteilungen", difficulty: 1, type: "input",
    question: "Münze 5×: $P(X=0$ Kopf$) = ?$",
    expectedAnswer: "0.03125", format: "Dezimalzahl",
    solution: "$\\binom{5}{0}(0{,}5)^5 = 0{,}03125$",
  },
  {
    id: "vt-2", lessonId: "m-verteilungen", difficulty: 2, type: "input",
    question: "Erwartungswert von $Bin(10, 0{,}3)$?",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "$E(X) = np = 10 \\cdot 0{,}3 = 3$",
  },
  {
    id: "vt-3", lessonId: "m-verteilungen", difficulty: 2, type: "input",
    question: "Varianz von $Bin(10, 0{,}3)$?",
    expectedAnswer: "2.1", format: "Dezimalzahl",
    solution: "$Var(X) = np(1-p) = 10 \\cdot 0{,}3 \\cdot 0{,}7 = 2{,}1$",
  },
  {
    id: "vt-4", lessonId: "m-verteilungen", difficulty: 2, type: "multiple",
    question: "Wie viel liegt in $\\mu \\pm 2\\sigma$?",
    options: [
      { label: "68%", value: "a" },
      { label: "95%", value: "b" },
      { label: "99,7%", value: "c" },
      { label: "50%", value: "d" },
    ],
    correctOption: "b",
    solution: "95% der Werte liegen in $\\mu \\pm 2\\sigma$",
  },
  {
    id: "vt-5", lessonId: "m-verteilungen", difficulty: 1, type: "input",
    question: "Poisson: $\\lambda = 4$. $P(X=0) = ?$",
    expectedAnswer: "0.0183", format: "Dezimalzahl",
    solution: "$e^{-4} \approx 0{,}0183$",
  },
  {
    id: "vt-6", lessonId: "m-verteilungen", difficulty: 3, type: "input",
    question: "Standardabweichung bei Varianz 9?",
    expectedAnswer: "3", format: "Ganze Zahl",
    solution: "$\\sigma = \\sqrt{9} = 3$",
  },
];

export const folgenExercises: Exercise[] = [
  {
    id: "fr-1", lessonId: "m-folgen", difficulty: 1, type: "input",
    question: "Arithmetisch: $a_1 = 3$, $d = 5$. $a_4 = ?$",
    expectedAnswer: "18", format: "Ganze Zahl",
    solution: "$a_4 = 3 + 3 \\cdot 5 = 18$",
  },
  {
    id: "fr-2", lessonId: "m-folgen", difficulty: 1, type: "input",
    question: "Geometrisch: $a_1 = 2$, $q = 3$. $a_3 = ?$",
    expectedAnswer: "18", format: "Ganze Zahl",
    solution: "$a_3 = 2 \\cdot 3^2 = 18$",
  },
  {
    id: "fr-3", lessonId: "m-folgen", difficulty: 2, type: "input",
    question: "$1 + 2 + 3 + ... + 100 = ?$",
    expectedAnswer: "5050", format: "Ganze Zahl",
    solution: "$S_{100} = \\frac{100}{2}(1+100) = 5050$",
  },
  {
    id: "fr-4", lessonId: "m-folgen", difficulty: 2, type: "input",
    question: "$1 + \\frac{1}{2} + \\frac{1}{4} + ... = ?$",
    expectedAnswer: "2", format: "Ganze Zahl",
    solution: "$S = \\frac{1}{1-\\frac{1}{2}} = 2$",
  },
  {
    id: "fr-5", lessonId: "m-folgen", difficulty: 2, type: "multiple",
    question: "Konvergiert $\\sum \\frac{1}{n}$?",
    options: [
      { label: "Ja", value: "a" },
      { label: "Nein", value: "b" },
    ],
    correctOption: "b",
    solution: "Die harmonische Reihe divergiert!",
  },
  {
    id: "fr-6", lessonId: "m-folgen", difficulty: 3, type: "input",
    question: "Arithmetisches Mittel von $2, 5, 8, 11$?",
    expectedAnswer: "6.5", format: "Dezimalzahl",
    solution: "$\\frac{26}{4} = 6{,}5$",
  },
];

export const analytischeGeometrieExercises: Exercise[] = [
  {
    id: "ag-1", lessonId: "m-anageo", difficulty: 1, type: "input",
    question: "Normalenvektor von $3x - 2y + z = 5$?",
    expectedAnswer: "(3, -2, 1)", format: "Vektor",
    solution: "$\\vec{n} = (3, -2, 1)$",
  },
  {
    id: "ag-2", lessonId: "m-anageo", difficulty: 2, type: "input",
    question: "Abstand $(0,0,0)$ zur Ebene $x+y+z=3$? (gerundet)",
    expectedAnswer: "$\\sqrt{3}$", format: "Wurzel",
    solution: "$d = \\frac{3}{\\sqrt{3}} = \\sqrt{3}$",
  },
  {
    id: "ag-3", lessonId: "m-anageo", difficulty: 2, type: "multiple",
    question: "Wie viele Parameter hat eine Gerade im Raum?",
    options: [
      { label: "1", value: "a" },
      { label: "2", value: "b" },
      { label: "3", value: "c" },
      { label: "0", value: "d" },
    ],
    correctOption: "a",
    solution: "Eine Gerade hat einen Parameter $t$.",
  },
  {
    id: "ag-4", lessonId: "m-anageo", difficulty: 3, type: "input",
    question: "Abstand $(1,2,3)$ zur Ebene $2x+y-2z=4$?",
    expectedAnswer: "2", format: "Ganze Zahl",
    solution: "$d = \\frac{|2+2-6-4|}{3} = \\frac{|-6|}{3} = 2$",
  },
  {
    id: "ag-5", lessonId: "m-anageo", difficulty: 2, type: "input",
    question: "Stützvektor: $\\vec{x} = (1,2,3) + t(4,5,6)$?",
    expectedAnswer: "(1, 2, 3)", format: "Vektor",
    solution: "$\\vec{p} = (1, 2, 3)$",
  },
  {
    id: "ag-6", lessonId: "m-anageo", difficulty: 3, type: "multiple",
    question: "Parallel wenn Richtungsvektoren...",
    options: [
      { label: "proportional", value: "a" },
      { label: "orthogonal", value: "b" },
      { label: "gleich", value: "c" },
      { label: "verschieden", value: "d" },
    ],
    correctOption: "a",
    solution: "Parallel: $\\vec{v}_1 = k \\cdot \\vec{v}_2$",
  },
];


// ==================== NEUE MODULE Exercises ====================

export const prozentExercises: Exercise[] = [
  { id: "pz-1", lessonId: "m-prozent", difficulty: 1, type: "input", question: "30% von 250?", expectedAnswer: "75", format: "Ganze Zahl", solution: "$250 \\cdot 0.3 = 75$" },
  { id: "pz-2", lessonId: "m-prozent", difficulty: 1, type: "input", question: "15% von 400?", expectedAnswer: "60", format: "Ganze Zahl", solution: "$400 \\cdot 0.15 = 60$" },
  { id: "pz-3", lessonId: "m-prozent", difficulty: 2, type: "input", question: "Preis 80->100. Steigerung?", expectedAnswer: "25", format: "Prozent", solution: "$20/80 = 25\%$" },
  { id: "pz-4", lessonId: "m-prozent", difficulty: 2, type: "input", question: "Zinsen: 5000, 4%, 1J?", expectedAnswer: "200", format: "Ganze Zahl", solution: "$5000 \\cdot 0.04 = 200$" },
  { id: "pz-5", lessonId: "m-prozent", difficulty: 2, type: "input", question: "Zinseszins: 1000, 3%, 2J?", expectedAnswer: "1060.9", format: "Dezimalzahl", solution: "$1000 \\cdot 1.03^2 = 1060.90$" },
  { id: "pz-6", lessonId: "m-prozent", difficulty: 3, type: "multiple", question: "Verdopplung bei 6%?", options: [{label: "6J", value: "a"}, {label: "12J", value: "b"}, {label: "18J", value: "c"}, {label: "24J", value: "d"}], correctOption: "b", solution: "72/6 = 12J" },
];

export const koerperExercises: Exercise[] = [
  { id: "ko-1", lessonId: "m-koerper", difficulty: 1, type: "input", question: "Quader 2x3x4?", expectedAnswer: "24", format: "Ganze Zahl", solution: "$2 \\cdot 3 \\cdot 4 = 24$" },
  { id: "ko-2", lessonId: "m-koerper", difficulty: 1, type: "input", question: "Oberflaeche Wuerfel a=3?", expectedAnswer: "54", format: "Ganze Zahl", solution: "$6 \\cdot 9 = 54$" },
  { id: "ko-3", lessonId: "m-koerper", difficulty: 2, type: "input", question: "Zylinder r=2, h=5?", expectedAnswer: "20pi", format: "Ausdruck", solution: "$V = \\pi \\cdot 4 \\cdot 5 = 20\\pi$" },
  { id: "ko-4", lessonId: "m-koerper", difficulty: 2, type: "input", question: "Kugel r=3?", expectedAnswer: "36pi", format: "Ausdruck", solution: "$V = \\frac{4}{3}\\pi \\cdot 27 = 36\\pi$" },
  { id: "ko-5", lessonId: "m-koerper", difficulty: 2, type: "multiple", question: "Kegel = ? des Zylinders", options: [{label: "1/2", value: "a"}, {label: "1/3", value: "b"}, {label: "1/4", value: "c"}], correctOption: "b", solution: "$V = \\frac{1}{3}V_{Zyl}$" },
  { id: "ko-6", lessonId: "m-koerper", difficulty: 3, type: "input", question: "Kugel-Oberflaeche r=5?", expectedAnswer: "100pi", format: "Ausdruck", solution: "$O = 4\\pi \\cdot 25 = 100\\pi$" },
];

export const kombinatorikExercises: Exercise[] = [
  { id: "kb-1", lessonId: "m-kombinatorik", difficulty: 1, type: "input", question: "$5! = ?$", expectedAnswer: "120", format: "Ganze Zahl", solution: "$5! = 120$" },
  { id: "kb-2", lessonId: "m-kombinatorik", difficulty: 1, type: "input", question: "C(6,2) = ?", expectedAnswer: "15", format: "Ganze Zahl", solution: "$\\binom{6}{2} = 15$" },
  { id: "kb-3", lessonId: "m-kombinatorik", difficulty: 2, type: "input", question: "V(6,3) = ?", expectedAnswer: "120", format: "Ganze Zahl", solution: "$6!/3! = 120$" },
  { id: "kb-4", lessonId: "m-kombinatorik", difficulty: 2, type: "input", question: "C(8,3) = ?", expectedAnswer: "56", format: "Ganze Zahl", solution: "$\\binom{8}{3} = 56$" },
  { id: "kb-5", lessonId: "m-kombinatorik", difficulty: 2, type: "multiple", question: "Permutationen AABB?", options: [{label: "24", value: "a"}, {label: "12", value: "b"}, {label: "6", value: "c"}, {label: "4", value: "d"}], correctOption: "c", solution: "$4!/(2!2!) = 6$" },
  { id: "kb-6", lessonId: "m-kombinatorik", difficulty: 3, type: "input", question: "Lotto 6 aus 49?", expectedAnswer: "13983816", format: "Ganze Zahl", solution: "$\\binom{49}{6} = 13983816$" },
];

export const logikExercises: Exercise[] = [
  { id: "lg-1", lessonId: "m-logik", difficulty: 1, type: "multiple", question: "w UND f = ?", options: [{label: "w", value: "a"}, {label: "f", value: "b"}], correctOption: "b", solution: "UND nur wahr wenn beide wahr" },
  { id: "lg-2", lessonId: "m-logik", difficulty: 1, type: "multiple", question: "f ODER w = ?", options: [{label: "w", value: "a"}, {label: "f", value: "b"}], correctOption: "a", solution: "ODER wahr wenn mind. eine wahr" },
  { id: "lg-3", lessonId: "m-logik", difficulty: 2, type: "multiple", question: "NICHT(w UND f) = ?", options: [{label: "w", value: "a"}, {label: "f", value: "b"}], correctOption: "a", solution: "NICHT(f) = w" },
  { id: "lg-4", lessonId: "m-logik", difficulty: 2, type: "multiple", question: "Kontraposition?", options: [{label: "q=>p", value: "a"}, {label: "~q=>~p", value: "b"}, {label: "~p=>~q", value: "c"}], correctOption: "b", solution: "~q => ~p" },
  { id: "lg-5", lessonId: "m-logik", difficulty: 2, type: "multiple", question: "De Morgan: ~(p oder q)?", options: [{label: "~p oder ~q", value: "a"}, {label: "~p und ~q", value: "b"}], correctOption: "b", solution: "~p und ~q" },
  { id: "lg-6", lessonId: "m-logik", difficulty: 3, type: "multiple", question: "VI-Schritt?", options: [{label: "Anfang", value: "a"}, {label: "n->n+1", value: "b"}, {label: "Widerspruch", value: "c"}], correctOption: "b", solution: "Induktionsschritt" },
];

export const dreisatzExercises: Exercise[] = [
  { id: "ds-1", lessonId: "m-dreisatz", difficulty: 1, type: "input", question: "3 Aepfel=2E. 9 Aepfel?", expectedAnswer: "6", format: "Ganze Zahl", solution: "$9 \\cdot 2 / 3 = 6$" },
  { id: "ds-2", lessonId: "m-dreisatz", difficulty: 1, type: "input", question: "5 Arb., 10T. 2 Arb.?", expectedAnswer: "25", format: "Ganze Zahl", solution: "$5 \\cdot 10 / 2 = 25$" },
  { id: "ds-3", lessonId: "m-dreisatz", difficulty: 2, type: "input", question: "4L=6E. 10L?", expectedAnswer: "15", format: "Ganze Zahl", solution: "$10 \\cdot 6 / 4 = 15$" },
  { id: "ds-4", lessonId: "m-dreisatz", difficulty: 2, type: "input", question: "6 Masch., 12h. 4 Masch.?", expectedAnswer: "18", format: "Ganze Zahl", solution: "$6 \\cdot 12 / 4 = 18$" },
  { id: "ds-5", lessonId: "m-dreisatz", difficulty: 2, type: "multiple", question: "Direkt proportional?", options: [{label: "Verhaeltnis", value: "a"}, {label: "Produkt", value: "b"}, {label: "Summe", value: "c"}], correctOption: "a", solution: "a1/b1 = a2/b2" },
  { id: "ds-6", lessonId: "m-dreisatz", difficulty: 3, type: "input", question: "8 Arb., 15T. 6 Arb.?", expectedAnswer: "20", format: "Ganze Zahl", solution: "$8 \\cdot 15 / 6 = 20$" },
];

export const taylorExercises: Exercise[] = [
  { id: "tw-1", lessonId: "m-taylor", difficulty: 1, type: "multiple", question: "Taylor bei a=0?", options: [{label: "Fourier", value: "a"}, {label: "Maclaurin", value: "b"}, {label: "Laurent", value: "c"}], correctOption: "b", solution: "Maclaurin-Reihe" },
  { id: "tw-2", lessonId: "m-taylor", difficulty: 1, type: "input", question: "$e^x \approx ?$ (1. Ord.)", expectedAnswer: "1+x", format: "Term", solution: "$e^x \approx 1+x$" },
  { id: "tw-3", lessonId: "m-taylor", difficulty: 2, type: "input", question: "$\\sin(x) \approx ?$ (1. Ord.)", expectedAnswer: "x", format: "Term", solution: "$\\sin(x) \approx x$" },
  { id: "tw-4", lessonId: "m-taylor", difficulty: 2, type: "multiple", question: "Konvergenzradius 1/(1-x)?", options: [{label: "R=0", value: "a"}, {label: "R=1", value: "b"}, {label: "R=inf", value: "c"}], correctOption: "b", solution: "|x|<1, R=1" },
  { id: "tw-5", lessonId: "m-taylor", difficulty: 2, type: "input", question: "$\\cos(x) \approx ?$ (2. Ord.)", expectedAnswer: "1-x^2/2", format: "Term", solution: "$\\cos(x) \approx 1 - x^2/2$" },
  { id: "tw-6", lessonId: "m-taylor", difficulty: 3, type: "input", question: "Glieder fuer $e \approx 2.7$?", expectedAnswer: "8", format: "Ganze Zahl", solution: "Ca. 8 Glieder" },
];


export const allExercises: Exercise[] = [
  ...grundlagenExercises,
  ...mathe1Exercises,
  ...mathe2Exercises,
  ...stochastikExercises,
  ...komplexeExercises,
  ...numerikExercises,
  ...geometrieExercises,
  ...trigonometrieExercises,
  ...potenzenExercises,
  ...statistikExercises,
  ...bruchrechnenExercises,
  ...gleichungenExercises,
  ...termumformungExercises,
  ...ungleichungenExercises,
  ...kurvendiskussionExercises,
  ...gleichungssystemeExercises,
  ...matrizenExercises,
  ...verteilungenExercises,
  ...folgenExercises,
  ...analytischeGeometrieExercises,
];

export function getExercisesForLesson(moduleId: string): Exercise[] {
  return allExercises.filter((e) => e.lessonId === moduleId);
}
