// Interaktive Mathe-Aufgaben für alle Module
export interface Exercise {
  id: string;
  lessonId: string;
  difficulty: 1 | 2 | 3;
  type: 'input' | 'multiple';
  question: string;
  hint?: string;
  expectedAnswer?: string;
  tolerance?: number;
  format?: string;
  options?: { label: string; value: string }[];
  correctOption?: string;
  solution: string;
}

// ==================== MATHE GRUNDLAGEN ====================

export const grundlagenExercises: Exercise[] = [
  // ===== m-grundlagen-mengen (mg1, mg2, mg3, mg4) =====
  // mg1: Mengen
  {
    id: "gr-mengen-1",
    lessonId: "m-grundlagen-mengen",
    difficulty: 1,
    type: "multiple",
    question: "Welche Menge ist eine Teilmenge von $A = \\{1, 2, 3\\}$?",
    options: [
      { label: "$\\{1, 4\\}$", value: "a" },
      { label: "$\\{1, 2\\}$", value: "b" },
      { label: "$\\{4, 5, 6\\}$", value: "c" },
      { label: "$\\mathbb{N}$", value: "d" },
    ],
    correctOption: "b",
    solution: "$\\{1, 2\\} \\subset A$, da alle Elemente auch in $A$ enthalten sind.",
  },
  {
    id: "gr-mengen-2",
    lessonId: "m-grundlagen-mengen",
    difficulty: 1,
    type: "input",
    question: "Wie viele Elemente hat $A = \\{2, 4, 6, 8\\}$?",
    expectedAnswer: "4",
    format: "Ganze Zahl",
    solution: "$|A| = 4$ (4 Elemente in der Menge).",
  },
  {
    id: "gr-mengen-3",
    lessonId: "m-grundlagen-mengen",
    difficulty: 2,
    type: "input",
    question: "Gegeben $A = \\{1, 2, 3, 4\\}$ und $B = \\{3, 4, 5, 6\\}$. Berechne $|A \\cup B|$.",
    expectedAnswer: "6",
    format: "Ganze Zahl",
    solution: "$A \\cup B = \\{1, 2, 3, 4, 5, 6\\}$, also $|A \\cup B| = 6$.",
  },
  {
    id: "gr-mengen-4",
    lessonId: "m-grundlagen-mengen",
    difficulty: 2,
    type: "input",
    question: "Gegeben $A = \\{1, 2, 3, 4\\}$ und $B = \\{3, 4, 5, 6\\}$. Berechne $|A \\cap B|$.",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "$A \\cap B = \\{3, 4\\}$, also $|A \\cap B| = 2$.",
  },
  {
    id: "gr-mengen-5",
    lessonId: "m-grundlagen-mengen",
    difficulty: 3,
    type: "input",
    question: "Gegeben $A = \\{1, 2, 3\\}$, $B = \\{2, 3, 4\\}$, $C = \\{3, 4, 5\\}$. Berechne $|(A \\cup B) \\cap C|$.",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "$A \\cup B = \\{1, 2, 3, 4\\}$. Dann $(A \\cup B) \\cap C = \\{3, 4\\}$, also 2.",
  },
  {
    id: "gr-mengen-6",
    lessonId: "m-grundlagen-mengen",
    difficulty: 3,
    type: "multiple",
    question: "Was ist $A \\setminus B$ wenn $A = \\{1, 2, 3, 4\\}$ und $B = \\{3, 4, 5\\}$?",
    options: [
      { label: "$\\{1, 2\\}$", value: "a" },
      { label: "$\\{5\\}$", value: "b" },
      { label: "$\\{1, 2, 5\\}$", value: "c" },
      { label: "$\\{3, 4\\}$", value: "d" },
    ],
    correctOption: "a",
    solution: "$A \\setminus B$ enthält Elemente in $A$ aber nicht in $B$: $\\{1, 2\\}$.",
  },

  // mg2: Logische Aussagen
  {
    id: "gr-logik-1",
    lessonId: "m-grundlagen-mengen",
    difficulty: 1,
    type: "multiple",
    question: "Was bedeutet $P \\land Q$?",
    options: [
      { label: "P oder Q", value: "a" },
      { label: "P und Q", value: "b" },
      { label: "Nicht P", value: "c" },
      { label: "P impliziert Q", value: "d" },
    ],
    correctOption: "b",
    solution: "$P \\land Q$ bedeutet \"P und Q\" - beide Aussagen müssen wahr sein.",
  },
  {
    id: "gr-logik-2",
    lessonId: "m-grundlagen-mengen",
    difficulty: 2,
    type: "multiple",
    question: "Wann ist $P \\rightarrow Q$ falsch?",
    options: [
      { label: "P wahr, Q wahr", value: "a" },
      { label: "P wahr, Q falsch", value: "b" },
      { label: "P falsch, Q wahr", value: "c" },
      { label: "P falsch, Q falsch", value: "d" },
    ],
    correctOption: "b",
    solution: "$P \\rightarrow Q$ ist nur falsch wenn P wahr und Q falsch ist.",
  },
  {
    id: "gr-logik-3",
    lessonId: "m-grundlagen-mengen",
    difficulty: 3,
    type: "multiple",
    question: "Was ist die Negation von $\\forall x: P(x)$?",
    options: [
      { label: "$\\forall x: \\neg P(x)$", value: "a" },
      { label: "$\\exists x: \\neg P(x)$", value: "b" },
      { label: "$\\exists x: P(x)$", value: "c" },
      { label: "$\\neg P(x)$", value: "d" },
    ],
    correctOption: "b",
    solution: "$\\neg(\\forall x: P(x)) \\equiv \\exists x: \\neg P(x)$ - De Morgan für Quantoren.",
  },

  // ===== m-grundlagen-funktionen (mf1, mf2, mf3) =====
  {
    id: "gr-func-1",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 1,
    type: "input",
    question: "Gegeben $f(x) = 2x + 3$. Berechne $f(4)$.",
    expectedAnswer: "11",
    format: "Ganze Zahl",
    solution: "$f(4) = 2 \\cdot 4 + 3 = 11$.",
  },
  {
    id: "gr-func-2",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 1,
    type: "input",
    question: "Gegeben $f(x) = x^2$. Berechne $f(3)$.",
    expectedAnswer: "9",
    format: "Ganze Zahl",
    solution: "$f(3) = 3^2 = 9$.",
  },
  {
    id: "gr-func-3",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 2,
    type: "multiple",
    question: "Was ist der Definitionsbereich von $f(x) = \\frac{1}{x-2}$?",
    options: [
      { label: "$\\mathbb{R}$", value: "a" },
      { label: "$\\mathbb{R} \\setminus \\{2\\}$", value: "b" },
      { label: "$\\mathbb{R} \\setminus \\{-2\\}$", value: "c" },
      { label: "$[2, \\infty)$", value: "d" },
    ],
    correctOption: "b",
    solution: "Nenner $\\neq 0$: $x - 2 \\neq 0 \\Rightarrow x \\neq 2$.",
  },
  {
    id: "gr-func-4",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 2,
    type: "multiple",
    question: "Welche Funktion ist gerade (achsensymmetrisch)?",
    options: [
      { label: "$f(x) = x + 1$", value: "a" },
      { label: "$f(x) = x^2$", value: "b" },
      { label: "$f(x) = x^3$", value: "c" },
      { label: "$f(x) = x + x^2$", value: "d" },
    ],
    correctOption: "b",
    solution: "Gerade: $f(-x) = f(x)$. Für $x^2$: $(-x)^2 = x^2$ ✅",
  },
  {
    id: "gr-func-5",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 3,
    type: "input",
    question: "Gegeben $f(x) = x^2 - 4x + 3$. Berechne $f(a+1)$ als Term in $a$ (ohne Leerzeichen).",
    expectedAnswer: "a^2-2a",
    format: "Term wie a^2-2a",
    solution: "$f(a+1) = (a+1)^2 - 4(a+1) + 3 = a^2 + 2a + 1 - 4a - 4 + 3 = a^2 - 2a$.",
  },
  {
    id: "gr-func-6",
    lessonId: "m-grundlagen-funktionen",
    difficulty: 3,
    type: "input",
    question: "Gegeben $f(x) = 3x - 1$. Finde $f^{-1}(5)$.",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "$y = 3x - 1 \\Rightarrow 5 = 3x - 1 \\Rightarrow x = 2$.",
  },
];

// ==================== MATHE 1 ====================

export const mathe1Exercises: Exercise[] = [
  // ===== m1-grenzwerte =====
  {
    id: "m1-gw-1",
    lessonId: "m1-grenzwerte",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\lim_{x \\to 3} (2x + 1)$.",
    expectedAnswer: "7",
    format: "Ganze Zahl",
    solution: "Einsetzen: $2 \\cdot 3 + 1 = 7$.",
  },
  {
    id: "m1-gw-2",
    lessonId: "m1-grenzwerte",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\lim_{x \\to 2} (x^2 + 1)$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "Einsetzen: $2^2 + 1 = 5$.",
  },
  {
    id: "m1-gw-3",
    lessonId: "m1-grenzwerte",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}$.",
    expectedAnswer: "4",
    format: "Ganze Zahl",
    solution: "$\\frac{(x-2)(x+2)}{x-2} = x+2$ für $x \\neq 2$. Also $2+2 = 4$.",
  },
  {
    id: "m1-gw-4",
    lessonId: "m1-grenzwerte",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\lim_{x \\to 0} \\frac{\\sin x}{x}$.",
    expectedAnswer: "1",
    format: "Ganze Zahl",
    solution: "Standardgrenzwert: $\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$.",
  },
  {
    id: "m1-gw-5",
    lessonId: "m1-grenzwerte",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\lim_{x \\to \\infty} \\frac{3x^2 + x}{2x^2 - 1}$. Gib eine Dezimalzahl auf 2 Stellen.",
    expectedAnswer: "1.50",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.50",
    solution: "Koeffizienten der höchsten Potenz: $\\frac{3}{2} = 1.5$.",
  },
  {
    id: "m1-gw-6",
    lessonId: "m1-grenzwerte",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\lim_{x \\to 0} \\frac{e^x - 1}{x}$. Dezimalzahl auf 2 Stellen.",
    expectedAnswer: "1.00",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.00",
    solution: "Standardgrenzwert: $\\lim_{x \\to 0} \\frac{e^x - 1}{x} = 1$.",
  },

  // ===== m1-ableitungen =====
  {
    id: "m1-diff-1",
    lessonId: "m1-ableitungen",
    difficulty: 1,
    type: "input",
    question: "Berechne die 1. Ableitung von $f(x) = x^3$. Gib den Term an.",
    expectedAnswer: "3x^2",
    format: "Term wie 3x^2",
    solution: "$f'(x) = 3x^2$ (Potenzregel).",
  },
  {
    id: "m1-diff-2",
    lessonId: "m1-ableitungen",
    difficulty: 1,
    type: "input",
    question: "Berechne $f'(x)$ für $f(x) = x^4$.",
    expectedAnswer: "4x^3",
    format: "Term wie 4x^3",
    solution: "$f'(x) = 4x^3$ (Potenzregel).",
  },
  {
    id: "m1-diff-3",
    lessonId: "m1-ableitungen",
    difficulty: 2,
    type: "input",
    question: "Berechne $f'(x)$ für $f(x) = (2x + 1)^3$. Gib den vereinfachten Term an.",
    expectedAnswer: "6(2x+1)^2",
    format: "Term wie 6(2x+1)^2",
    solution: "Kettenregel: $f'(x) = 3(2x+1)^2 \\cdot 2 = 6(2x+1)^2$.",
  },
  {
    id: "m1-diff-4",
    lessonId: "m1-ableitungen",
    difficulty: 2,
    type: "multiple",
    question: "Was ist die Ableitung von $f(x) = \\sin(x)$?",
    options: [
      { label: "$\\cos(x)$", value: "a" },
      { label: "$-\\sin(x)$", value: "b" },
      { label: "$-\\cos(x)$", value: "c" },
      { label: "$\\tan(x)$", value: "d" },
    ],
    correctOption: "a",
    solution: "$f'(x) = \\cos(x)$ - Grundableitung.",
  },
  {
    id: "m1-diff-5",
    lessonId: "m1-ableitungen",
    difficulty: 3,
    type: "input",
    question: "Berechne $f'(x)$ für $f(x) = x^2 \\cdot e^x$. Gib den Term an.",
    expectedAnswer: "xe^x(x+2)",
    format: "Faktorisierte Form",
    solution: "Produktregel: $f'(x) = 2x \\cdot e^x + x^2 \\cdot e^x = xe^x(x+2)$.",
  },
  {
    id: "m1-diff-6",
    lessonId: "m1-ableitungen",
    difficulty: 3,
    type: "input",
    question: "Berechne die 2. Ableitung von $f(x) = x^3 - 2x^2 + x$.",
    expectedAnswer: "6x-4",
    format: "Term wie 6x-4",
    solution: "$f'(x) = 3x^2 - 4x + 1$, $f''(x) = 6x - 4$.",
  },

  // ===== m1-integration =====
  {
    id: "m1-int-1",
    lessonId: "m1-integration",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\int 2x \\, dx$. Gib den Term an (+C nicht nötig).",
    expectedAnswer: "x^2",
    format: "Term wie x^2",
    solution: "$\\int 2x \\, dx = x^2 + C$ (Potenzregel umgekehrt).",
  },
  {
    id: "m1-int-2",
    lessonId: "m1-integration",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\int x^2 \\, dx$. Gib den Term an.",
    expectedAnswer: "x^3/3",
    format: "Term wie x^3/3",
    solution: "$\\int x^2 \\, dx = \\frac{x^3}{3} + C$.",
  },
  {
    id: "m1-int-3",
    lessonId: "m1-integration",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\int_0^2 x^2 \\, dx$. Gib eine Dezimalzahl auf 2 Stellen.",
    expectedAnswer: "2.67",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 2.67",
    solution: "$\\left[\\frac{x^3}{3}\\right]_0^2 = \\frac{8}{3} \\approx 2.67$.",
  },
  {
    id: "m1-int-4",
    lessonId: "m1-integration",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\int_1^3 2x \\, dx$.",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "$\\left[x^2\\right]_1^3 = 9 - 1 = 8$.",
  },
  {
    id: "m1-int-5",
    lessonId: "m1-integration",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\int_0^1 (3x^2 + 2x) \\, dx$.",
    expectedAnswer: "2",
    format: "Ganze Zahl oder Dezimal",
    solution: "$\\left[x^3 + x^2\\right]_0^1 = (1 + 1) - 0 = 2$.",
  },
  {
    id: "m1-int-6",
    lessonId: "m1-integration",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\int e^{2x} \\, dx$. Gib den Term an.",
    expectedAnswer: "e^{2x}/2",
    format: "Term wie e^{2x}/2",
    solution: "$\\int e^{2x} \\, dx = \\frac{e^{2x}}{2} + C$ (Substitution $u = 2x$).",
  },

  // ===== m1-reihen =====
  {
    id: "m1-reihe-1",
    lessonId: "m1-reihen",
    difficulty: 1,
    type: "input",
    question: "Summe der ersten 5 Glieder: $a_n = 2n$ für $n = 1$ bis $5$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$2 + 4 + 6 + 8 + 10 = 30$.",
  },
  {
    id: "m1-reihe-2",
    lessonId: "m1-reihen",
    difficulty: 1,
    type: "input",
    question: "Summe: $\\sum_{n=1}^{4} n^2$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$1 + 4 + 9 + 16 = 30$.",
  },
  {
    id: "m1-reihe-3",
    lessonId: "m1-reihen",
    difficulty: 2,
    type: "multiple",
    question: "Welche Reihe konvergiert?",
    options: [
      { label: "$\\sum_{n=1}^{\\infty} n$", value: "a" },
      { label: "$\\sum_{n=1}^{\\infty} \\frac{1}{n}$", value: "b" },
      { label: "$\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$", value: "c" },
      { label: "$\\sum_{n=1}^{\\infty} 2^n$", value: "d" },
    ],
    correctOption: "c",
    solution: "$\\sum \\frac{1}{n^2}$ konvergiert (p-Reihe mit $p = 2 > 1$).",
  },
  {
    id: "m1-reihe-4",
    lessonId: "m1-reihen",
    difficulty: 2,
    type: "input",
    question: "Summe der geometrischen Reihe: $a_1 = 2$, $q = 0.5$. Gib die Grenze an.",
    expectedAnswer: "4",
    format: "Ganze oder Dezimalzahl",
    solution: "$S = \\frac{a_1}{1-q} = \\frac{2}{0.5} = 4$.",
  },
  {
    id: "m1-reihe-5",
    lessonId: "m1-reihen",
    difficulty: 3,
    type: "input",
    question: "Grenzwert der geometrischen Reihe $\\sum_{n=0}^{\\infty} (\\frac{1}{3})^n$. Dezimal auf 2 Stellen.",
    expectedAnswer: "1.50",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.50",
    solution: "$S = \\frac{a}{1-q} = \\frac{1}{1 - 1/3} = \\frac{3}{2} = 1.5$.",
  },
  {
    id: "m1-reihe-6",
    lessonId: "m1-reihen",
    difficulty: 3,
    type: "multiple",
    question: "Welches Konvergenzkriterium ist korrekt für $\\sum \\frac{1}{n^2}$?",
    options: [
      { label: "Quotientenkriterium: $q = 1$", value: "a" },
      { label: "p-Reihe mit $p = 2 > 1$", value: "b" },
      { label: "Leibniz-Kriterium", value: "c" },
      { label: "Divergenz durch $a_n \\to 0$", value: "d" },
    ],
    correctOption: "b",
    solution: "$\\sum \\frac{1}{n^p}$ konvergiert für $p > 1$. Hier $p = 2$.",
  },
];

// ==================== MATHE 2 ====================

export const mathe2Exercises: Exercise[] = [
  // ===== m2-vektoren =====
  {
    id: "m2-vec-1",
    lessonId: "m2-vektoren",
    difficulty: 1,
    type: "input",
    question: "$\\vec{a} = \\binom{2}{3}$, $\\vec{b} = \\binom{1}{4}$. Berechne $\\vec{a} + \\vec{b}$ (erster Eintrag).",
    expectedAnswer: "3",
    format: "Ganze Zahl",
    solution: "$\\vec{a} + \\vec{b} = \\binom{2+1}{3+4} = \\binom{3}{7}$. Erster Eintrag: 3.",
  },
  {
    id: "m2-vec-2",
    lessonId: "m2-vektoren",
    difficulty: 1,
    type: "input",
    question: "$\\vec{a} = \\binom{3}{4}$. Berechne $|\\vec{a}|$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "$|\\vec{a}| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = \\sqrt{25} = 5$.",
  },
  {
    id: "m2-vec-3",
    lessonId: "m2-vektoren",
    difficulty: 2,
    type: "input",
    question: "$\\vec{a} = \\binom{3}{1}$, $\\vec{b} = \\binom{2}{-5}$. Berechne $\\vec{a} \\cdot \\vec{b}$.",
    expectedAnswer: "1",
    format: "Ganze Zahl",
    solution: "$\\vec{a} \\cdot \\vec{b} = 3 \\cdot 2 + 1 \\cdot (-5) = 6 - 5 = 1$.",
  },
  {
    id: "m2-vec-4",
    lessonId: "m2-vektoren",
    difficulty: 2,
    type: "multiple",
    question: "Wann sind zwei Vektoren orthogonal?",
    options: [
      { label: "Wenn sie parallel sind", value: "a" },
      { label: "Wenn ihr Skalarprodukt = 0 ist", value: "b" },
      { label: "Wenn sie gleich lang sind", value: "c" },
      { label: "Wenn ihre Summe = 0 ist", value: "d" },
    ],
    correctOption: "b",
    solution: "Orthogonal: $\\vec{a} \\cdot \\vec{b} = 0$ (Winkel = 90°).",
  },
  {
    id: "m2-vec-5",
    lessonId: "m2-vektoren",
    difficulty: 3,
    type: "input",
    question: "$\\vec{a} = \\binom{1}{2}{3}$, $\\vec{b} = \\binom{4}{5}{6}$. Berechne $\\vec{a} \\cdot \\vec{b}$.",
    expectedAnswer: "32",
    format: "Ganze Zahl",
    solution: "$\\vec{a} \\cdot \\vec{b} = 1 \\cdot 4 + 2 \\cdot 5 + 3 \\cdot 6 = 4 + 10 + 18 = 32$.",
  },
  {
    id: "m2-vec-6",
    lessonId: "m2-vektoren",
    difficulty: 3,
    type: "input",
    question: "Betrag von $\\vec{a} = \\binom{1}{2}{3}$. Dezimal auf 2 Stellen.",
    expectedAnswer: "3.74",
    tolerance: 0.01,
    format: "Dezimal, z.B. 3.74",
    solution: "$|\\vec{a}| = \\sqrt{1 + 4 + 9} = \\sqrt{14} \\approx 3.74$.",
  },

  // ===== m2-dgl =====
  {
    id: "m2-dgl-1",
    lessonId: "m2-dgl",
    difficulty: 1,
    type: "multiple",
    question: "Welche Funktion ist Lösung von $y' = 2y$?",
    options: [
      { label: "$y = 2x$", value: "a" },
      { label: "$y = e^{2x}$", value: "b" },
      { label: "$y = x^2$", value: "c" },
      { label: "$y = 2^x$", value: "d" },
    ],
    correctOption: "b",
    solution: "$y = e^{2x}$ → $y' = 2e^{2x} = 2y$. ✅",
  },
  {
    id: "m2-dgl-2",
    lessonId: "m2-dgl",
    difficulty: 1,
    type: "multiple",
    question: "Was ist eine homogene lineare DGL 1. Ordnung?",
    options: [
      { label: "$y' + y = x$", value: "a" },
      { label: "$y' + y = 0$", value: "b" },
      { label: "$y' = y^2$", value: "c" },
      { label: "$y'' + y = 0$", value: "d" },
    ],
    correctOption: "b",
    solution: "Homogen: Rechte Seite = 0. $y' + y = 0$ ist homogen linear 1. Ordnung.",
  },
  {
    id: "m2-dgl-3",
    lessonId: "m2-dgl",
    difficulty: 2,
    type: "input",
    question: "Löse $y' = 3y$, $y(0) = 2$. Berechne $y(1)$ auf 2 Stellen.",
    expectedAnswer: "40.17",
    tolerance: 0.1,
    format: "Dezimalzahl, z.B. 40.17",
    solution: "$y = 2e^{3x}$. $y(1) = 2e^3 \\approx 40.17$.",
  },
  {
    id: "m2-dgl-4",
    lessonId: "m2-dgl",
    difficulty: 2,
    type: "multiple",
    question: "Was ist die allgemeine Lösung von $y' = ky$?",
    options: [
      { label: "$y = kx + C$", value: "a" },
      { label: "$y = Ce^{kx}$", value: "b" },
      { label: "$y = Ck^x$", value: "c" },
      { label: "$y = e^{kx} + C$", value: "d" },
    ],
    correctOption: "b",
    solution: "Lösung: $y = Ce^{kx}$ (Exponentialfunktion).",
  },
  {
    id: "m2-dgl-5",
    lessonId: "m2-dgl",
    difficulty: 3,
    type: "input",
    question: "Löse $y' = xy$, $y(0) = 1$. Gib $y(2)$ auf 2 Stellen an.",
    expectedAnswer: "7.39",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 7.39",
    solution: "$y = e^{x^2/2}$. $y(2) = e^2 \\approx 7.39$.",
  },
  {
    id: "m2-dgl-6",
    lessonId: "m2-dgl",
    difficulty: 3,
    type: "input",
    question: "Löse $y'' - 3y' + 2y = 0$. Gib die charakteristische Gleichung als Term an (z.B. r^2-3r+2=0).",
    expectedAnswer: "r^2-3r+2=0",
    format: "Gleichung wie r^2-3r+2=0",
    solution: "Charakteristisch: $r^2 - 3r + 2 = 0$ → $(r-1)(r-2) = 0$ → $r_1 = 1, r_2 = 2$.",
  },
];

// ==================== GEOMETRIE ====================

export const geometrieExercises: Exercise[] = [
  {
    id: "geo-1",
    lessonId: "m-geometrie-flaechen",
    difficulty: 1,
    type: "input",
    question: "Berechne die Fläche eines Rechtecks mit $a = 7\\text{cm}$ und $b = 3\\text{cm}$.",
    expectedAnswer: "21",
    format: "Ganze Zahl",
    solution: "$A = a \\cdot b = 7 \\cdot 3 = 21\\text{cm}^2$.",
  },
  {
    id: "geo-2",
    lessonId: "m-geometrie-flaechen",
    difficulty: 1,
    type: "input",
    question: "Berechne die Fläche eines Dreiecks mit Grundseite $g = 10$ und Höhe $h = 6$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$A = \\frac{g \\cdot h}{2} = \\frac{10 \\cdot 6}{2} = 30$.",
  },
  {
    id: "geo-3",
    lessonId: "m-geometrie-flaechen",
    difficulty: 2,
    type: "input",
    question: "Berechne die Fläche eines Kreises mit Radius $r = 4$. Gib den Faktor vor $\\pi$ an.",
    expectedAnswer: "16",
    format: "Ganze Zahl",
    solution: "$A = \\pi r^2 = 16\\pi$. Der Faktor ist 16.",
  },
  {
    id: "geo-4",
    lessonId: "m-geometrie-flaechen",
    difficulty: 2,
    type: "input",
    question: "Berechne das Volumen eines Quaders mit $a=3$, $b=4$, $c=5$.",
    expectedAnswer: "60",
    format: "Ganze Zahl",
    solution: "$V = a \\cdot b \\cdot c = 3 \\cdot 4 \\cdot 5 = 60$.",
  },
  {
    id: "geo-5",
    lessonId: "m-geometrie-flaechen",
    difficulty: 3,
    type: "input",
    question: "Im rechtwinkligen Dreieck: $a = 8$, $b = 15$. Berechne die Hypotenuse $c$.",
    expectedAnswer: "17",
    format: "Ganze Zahl",
    solution: "Pythagoras: $c = \\sqrt{8^2 + 15^2} = \\sqrt{64 + 225} = \\sqrt{289} = 17$.",
  },
  {
    id: "geo-6",
    lessonId: "m-geometrie-flaechen",
    difficulty: 3,
    type: "input",
    question: "Berechne das Volumen einer Kugel mit $r = 3$. Gib den Faktor vor $\\pi$ an.",
    expectedAnswer: "36",
    format: "Ganze Zahl",
    solution: "$V = \\frac{4}{3}\\pi r^3 = \\frac{4}{3}\\pi \\cdot 27 = 36\\pi$. Der Faktor ist 36.",
  },
];

// ==================== TRIGONOMETRIE ====================

export const trigonometrieExercises: Exercise[] = [
  {
    id: "trig-1",
    lessonId: "m-trigonometrie",
    difficulty: 1,
    type: "input",
    question: "Was ist $\\sin(90°)$?",
    expectedAnswer: "1",
    format: "Ganze Zahl oder Dezimal",
    solution: "$\\sin(90°) = 1$.",
  },
  {
    id: "trig-2",
    lessonId: "m-trigonometrie",
    difficulty: 1,
    type: "input",
    question: "Im rechtwinkligen Dreieck: Gegenkathete $= 3$, Hypotenuse $= 5$. Berechne $\\sin(\\alpha)$ als Bruch (z.B. 3/5).",
    expectedAnswer: "3/5",
    format: "Bruch wie 3/5",
    solution: "$\\sin(\\alpha) = \\frac{3}{5}$.",
  },
  {
    id: "trig-3",
    lessonId: "m-trigonometrie",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\cos(60°)$ als Bruch (z.B. 1/2).",
    expectedAnswer: "1/2",
    format: "Bruch wie 1/2",
    solution: "$\\cos(60°) = \\frac{1}{2}$.",
  },
  {
    id: "trig-4",
    lessonId: "m-trigonometrie",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\tan(45°)$.",
    expectedAnswer: "1",
    format: "Ganze Zahl",
    solution: "$\\tan(45°) = \\frac{\\sin(45°)}{\\cos(45°)} = 1$.",
  },
  {
    id: "trig-5",
    lessonId: "m-trigonometrie",
    difficulty: 3,
    type: "input",
    question: "Gegeben: $a = 5$, $b = 7$, $\\gamma = 60°$. Berechne $c^2$ (Satz des Kosinus).",
    expectedAnswer: "39",
    format: "Ganze Zahl",
    solution: "$c^2 = a^2 + b^2 - 2ab\\cos(\\gamma) = 25 + 49 - 70 \\cdot 0.5 = 74 - 35 = 39$.",
  },
  {
    id: "trig-6",
    lessonId: "m-trigonometrie",
    difficulty: 3,
    type: "input",
    question: "Im rechtwinkligen Dreieck: $a = 6$, $c = 10$. Berechne $\\cos(\\alpha)$ als Dezimalzahl.",
    expectedAnswer: "0.8",
    format: "Dezimalzahl",
    solution: "$b = \\sqrt{100 - 36} = 8$. $\\cos(\\alpha) = \\frac{b}{c} = \\frac{8}{10} = 0.8$.",
  },
];

// ==================== POTENZEN ====================

export const potenzenExercises: Exercise[] = [
  {
    id: "pot-1",
    lessonId: "m-potenzen-log",
    difficulty: 1,
    type: "input",
    question: "Berechne $2^5$.",
    expectedAnswer: "32",
    format: "Ganze Zahl",
    solution: "$2^5 = 2 \\cdot 2 \\cdot 2 \\cdot 2 \\cdot 2 = 32$.",
  },
  {
    id: "pot-2",
    lessonId: "m-potenzen-log",
    difficulty: 1,
    type: "input",
    question: "Berechne $\\log_{10}(1000)$.",
    expectedAnswer: "3",
    format: "Ganze Zahl",
    solution: "$10^3 = 1000$, also $\\log_{10}(1000) = 3$.",
  },
  {
    id: "pot-3",
    lessonId: "m-potenzen-log",
    difficulty: 2,
    type: "input",
    question: "Vereinfache $\\frac{2^8}{2^5}$.",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "$\\frac{2^8}{2^5} = 2^{8-5} = 2^3 = 8$.",
  },
  {
    id: "pot-4",
    lessonId: "m-potenzen-log",
    difficulty: 2,
    type: "input",
    question: "Berechne $\\sqrt{144}$.",
    expectedAnswer: "12",
    format: "Ganze Zahl",
    solution: "$\\sqrt{144} = 12$, da $12^2 = 144$.",
  },
  {
    id: "pot-5",
    lessonId: "m-potenzen-log",
    difficulty: 3,
    type: "input",
    question: "Löse: $3^x = 81$.",
    expectedAnswer: "4",
    format: "Ganze Zahl",
    solution: "$81 = 3^4$, also $x = 4$.",
  },
  {
    id: "pot-6",
    lessonId: "m-potenzen-log",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\ln(e^5)$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "$\\ln(e^5) = 5$ (ln und $e^x$ sind Umkehrfunktionen).",
  },
];

// ==================== STATISTIK ====================

export const statistikExercises: Exercise[] = [
  {
    id: "stat-1",
    lessonId: "m-statistik",
    difficulty: 1,
    type: "input",
    question: "Berechne den Mittelwert von $4, 8, 12$.",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "$\\bar{x} = \\frac{4+8+12}{3} = \\frac{24}{3} = 8$.",
  },
  {
    id: "stat-2",
    lessonId: "m-statistik",
    difficulty: 1,
    type: "input",
    question: "Was ist der Median von $2, 5, 9$?",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "Sortiert: $2, 5, 9$. Der mittlere Wert ist 5.",
  },
  {
    id: "stat-3",
    lessonId: "m-statistik",
    difficulty: 2,
    type: "input",
    question: "Berechne den Mittelwert von $10, 20, 30, 40, 50$.",
    expectedAnswer: "30",
    format: "Ganze Zahl",
    solution: "$\\bar{x} = \\frac{10+20+30+40+50}{5} = \\frac{150}{5} = 30$.",
  },
  {
    id: "stat-4",
    lessonId: "m-statistik",
    difficulty: 2,
    type: "input",
    question: "Daten: $2, 4, 6$. Berechne die Varianz $s^2$.",
    expectedAnswer: "2.67",
    tolerance: 0.01,
    format: "Dezimalzahl",
    solution: "$\\bar{x} = 4$. $s^2 = \\frac{(2-4)^2+(4-4)^2+(6-4)^2}{3} = \\frac{4+0+4}{3} = \\frac{8}{3} \\approx 2.67$.",
  },
  {
    id: "stat-5",
    lessonId: "m-statistik",
    difficulty: 3,
    type: "input",
    question: "Daten: $1, 2, 3, 4, 5$. Berechne die Standardabweichung $s$ auf 2 Stellen.",
    expectedAnswer: "1.41",
    tolerance: 0.01,
    format: "Dezimalzahl, z.B. 1.41",
    solution: "$\\bar{x} = 3$. $s^2 = \\frac{4+1+0+1+4}{5} = 2$. $s = \\sqrt{2} \\approx 1.41$.",
  },
  {
    id: "stat-6",
    lessonId: "m-statistik",
    difficulty: 3,
    type: "input",
    question: "Daten: $3, 5, 7, 9, 11, 13$. Was ist der Median?",
    expectedAnswer: "8",
    format: "Ganze Zahl",
    solution: "Gerade Anzahl: Median = $\\frac{7+9}{2} = 8$.",
  },
];

// Alle zusammen

// ==================== STOCHASTIK ====================

export const stochastikExercises: Exercise[] = [
  {
    id: "sto-1",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Ein fairer Würfel wird geworfen. Wie groß ist $P(\\text{gerade Zahl})$? Gib den Bruch an (z.B. 1/2).",
    expectedAnswer: "1/2",
    format: "Bruch wie 1/2",
    solution: "Gerade Zahlen: {2, 4, 6} = 3 von 6. Also $P = 3/6 = 1/2$.",
  },
  {
    id: "sto-2",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Aus einem Kartenspiel (52 Karten) wird eine gezogen. Wie groß ist $P(\\text{Herz})$? Gib den Bruch an.",
    expectedAnswer: "1/4",
    format: "Bruch wie 1/4",
    solution: "Herz: 13 von 52 Karten. $P = 13/52 = 1/4$.",
  },
  {
    id: "sto-3",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "$P(A) = 0.6$, $P(B) = 0.4$, $P(A \\cap B) = 0.2$. Berechne $P(A \\cup B)$.",
    expectedAnswer: "0.8",
    format: "Dezimalzahl",
    solution: "Additionssatz: $P(A \\cup B) = 0.6 + 0.4 - 0.2 = 0.8$.",
  },
  {
    id: "sto-4",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "Wie viele 3-stellige Zahlen kann man aus {1,2,3,4,5} bilden ohne Wiederholung?",
    expectedAnswer: "60",
    format: "Ganze Zahl",
    solution: "Variation ohne Zurücklegen: $V_3^5 = 5 \\cdot 4 \\cdot 3 = 60$.",
  },
  {
    id: "sto-5",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "In einer Urne sind 6 rote und 4 blaue Kugeln. Zwei werden gezogen (ohne Zurücklegen). Wie groß ist $P(\\text{beide rot})$? Gib den Bruch an.",
    expectedAnswer: "1/3",
    format: "Bruch wie 1/3",
    solution: "$P = \\frac{6}{10} \\cdot \\frac{5}{9} = \\frac{30}{90} = \\frac{1}{3}$.",
  },
  {
    id: "sto-6",
    lessonId: "m-stochastik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "Wie viele Kombinationen von 5 aus 10 Objekten gibt es? $\\binom{10}{5}$?",
    expectedAnswer: "252",
    format: "Ganze Zahl",
    solution: "$\\binom{10}{5} = \\frac{10!}{5! \\cdot 5!} = 252$.",
  },
];

// ==================== KOMPLEXE ZAHLEN ====================

export const komplexeExercises: Exercise[] = [
  {
    id: "kz-1",
    lessonId: "m-komplexe-zahlen",
    difficulty: 1,
    type: "input",
    question: "Berechne $(3 + 2i) + (1 - 4i)$. Gib im Format a+bi an (z.B. 4-2i).",
    expectedAnswer: "4-2i",
    format: "Format: a+bi",
    solution: "$(3+1) + (2-4)i = 4 - 2i$.",
  },
  {
    id: "kz-2",
    lessonId: "m-komplexe-zahlen",
    difficulty: 1,
    type: "input",
    question: "Was ist der Realteil von $z = -3 + 5i$?",
    expectedAnswer: "-3",
    format: "Ganze Zahl",
    solution: "Re(z) = -3.",
  },
  {
    id: "kz-3",
    lessonId: "m-komplexe-zahlen",
    difficulty: 2,
    type: "input",
    question: "Berechne $(2 + i)(3 - i)$. Gib im Format a+bi an.",
    expectedAnswer: "7+i",
    format: "Format: a+bi",
    solution: "$(2+i)(3-i) = 6 - 2i + 3i - i^2 = 6 + i + 1 = 7 + i$.",
  },
  {
    id: "kz-4",
    lessonId: "m-komplexe-zahlen",
    difficulty: 2,
    type: "input",
    question: "Berechne den Betrag von $z = 3 + 4i$.",
    expectedAnswer: "5",
    format: "Ganze Zahl",
    solution: "$|z| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = \\sqrt{25} = 5$.",
  },
  {
    id: "kz-5",
    lessonId: "m-komplexe-zahlen",
    difficulty: 3,
    type: "input",
    question: "Berechne $\\frac{2+i}{1-i}$. Gib im Format a+bi an.",
    expectedAnswer: "0.5+1.5i",
    format: "Format wie 0.5+1.5i",
    solution: "$\\frac{(2+i)(1+i)}{(1-i)(1+i)} = \\frac{2+2i+i+i^2}{2} = \\frac{1+3i}{2} = 0.5 + 1.5i$.",
  },
  {
    id: "kz-6",
    lessonId: "m-komplexe-zahlen",
    difficulty: 3,
    type: "input",
    question: "Gib $z = 1 + \\sqrt{3}i$ in Polardarstellung an (Betrag, Winkel in Grad).",
    expectedAnswer: "2,60",
    tolerance: 1,
    format: "Betrag,Winkel (z.B. 2,60)",
    solution: "$r = \\sqrt{1+3} = 2$, $\\varphi = \\arctan(\\sqrt{3}) = 60°$. Also $z = 2e^{i60°}$.",
  },
];

// ==================== NUMERIK ====================

export const numerikExercises: Exercise[] = [
  {
    id: "num-1",
    lessonId: "m-numerik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Berechne den absoluten Fehler für $x_{exakt} = 5$, $x_{approx} = 4.98$.",
    expectedAnswer: "0.02",
    format: "Dezimalzahl",
    solution: "$|5 - 4.98| = 0.02$.",
  },
  {
    id: "num-2",
    lessonId: "m-numerik-grundlagen",
    difficulty: 1,
    type: "input",
    question: "Berechne den relativen Fehler in % für $x_{exakt} = 100$, $x_{approx} = 98$.",
    expectedAnswer: "2",
    format: "Dezimalzahl",
    solution: "$\\frac{|100-98|}{100} = 0.02 = 2\\%$.",
  },
  {
    id: "num-3",
    lessonId: "m-numerik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "Bisektion: $f(x) = x^2 - 4$ auf [1,3]. Nach 3 Schritten: Was ist die neue obere Grenze b?",
    expectedAnswer: "2",
    format: "Ganze Zahl",
    solution: "Schritt 1: m=2, f(2)=0 → fertig! Oder: $b=2$ wenn $f(a)\\cdot f(m) < 0$.",
  },
  {
    id: "num-4",
    lessonId: "m-numerik-grundlagen",
    difficulty: 2,
    type: "input",
    question: "Newton: $f(x) = x^2 - 9$, $x_0 = 4$. Berechne $x_1$.",
    expectedAnswer: "4.125",
    tolerance: 0.01,
    format: "Dezimalzahl",
    solution: "$f'(x) = 2x$. $x_1 = 4 - \\frac{16-9}{8} = 4 - 0.875 = 3.125$.",
  },
  {
    id: "num-5",
    lessonId: "m-numerik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "Newton: $f(x) = x^3 - 5$, $x_0 = 2$. Berechne $x_1$ auf 3 Stellen.",
    expectedAnswer: "2.083",
    tolerance: 0.01,
    format: "Dezimalzahl",
    solution: "$f'(x) = 3x^2$. $x_1 = 2 - \\frac{8-5}{12} = 2 - 0.25 = 1.75$.",
  },
  {
    id: "num-6",
    lessonId: "m-numerik-grundlagen",
    difficulty: 3,
    type: "input",
    question: "Wie viele Bisektionsschritte braucht man für Genauigkeit $10^{-6}$ auf [0,10]?",
    expectedAnswer: "24",
    format: "Ganze Zahl",
    solution: "$\\frac{10}{2^n} < 10^{-6}$ → $2^n > 10^7$ → $n > \\log_2(10^7) \\approx 23.25$ → $n = 24$.",
  },
];
export const allExercises: Exercise[] = [
  ...grundlagenExercises,
  ...mathe1Exercises,
  ...mathe2Exercises,
  ...stochastikExercises,
  ...komplexeExercises,
  ...numerikExercises,
  ...geometrieExercises,
  ...trigonometrieExercises,
  ...potenzenExercises,
  ...statistikExercises,
];

export function getExercisesForLesson(moduleId: string): Exercise[] {
  return allExercises.filter((e) => e.lessonId === moduleId);
}
