/**
 * generate-module-registry.ts
 *
 * Scans lib/content/ for module files and generates lib/content/registry.ts
 * with auto-discovered imports. Run this after adding new modules.
 *
 * Usage: npx ts-node scripts/generate-module-registry.ts
 */

import * as fs from "fs";
import * as path from "path";

const CONTENT_DIR = path.join(__dirname, "..", "lib", "content");
const OUTPUT_FILE = path.join(CONTENT_DIR, "registry.ts");

interface ModuleFile {
  category: string;
  filename: string;
  varName: string;
}

function scanContent(): ModuleFile[] {
  const modules: ModuleFile[] = [];

  if (!fs.existsSync(CONTENT_DIR)) {
    return modules;
  }

  const categories = fs.readdirSync(CONTENT_DIR).filter((f) => {
    const stat = fs.statSync(path.join(CONTENT_DIR, f));
    return stat.isDirectory();
  });

  for (const category of categories) {
    const categoryDir = path.join(CONTENT_DIR, category);
    const files = fs.readdirSync(categoryDir).filter((f) => {
      return f.endsWith(".ts") && f !== "index.ts" && !f.startsWith(".");
    });

    for (const file of files) {
      const filename = file.replace(".ts", "");
      const varName = `${category}_${filename}`.replace(/[^a-zA-Z0-9_]/g, "_");
      modules.push({ category, filename, varName });
    }
  }

  return modules.sort((a, b) => a.category.localeCompare(b.category) || a.filename.localeCompare(b.filename));
}

function generateRegistry(modules: ModuleFile[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/generate-module-registry.ts',
    '// Do not edit manually. Run: npx ts-node scripts/generate-module-registry.ts',
    '',
    'import { Module } from "../types";',
    '',
  ];

  for (const mod of modules) {
    lines.push(`import { module as ${mod.varName} } from "./${mod.category}/${mod.filename}";`);
  }

  lines.push('');
  lines.push('export const contentModules: Module[] = [');
  for (const mod of modules) {
    lines.push(`  ${mod.varName},`);
  }
  lines.push('];');
  lines.push('');

  return lines.join("\n");
}

const modules = scanContent();
const registry = generateRegistry(modules);

fs.writeFileSync(OUTPUT_FILE, registry, "utf-8");
console.log(`Generated ${OUTPUT_FILE} with ${modules.length} module(s)`);

if (modules.length === 0) {
  console.log("No modules found in lib/content/. Add .ts files to get started.");
  console.log("Example: lib/content/math/mein-modul.ts");
}
