import { Module } from "../types";

export const thowlADModule: Module = {
  id: "thowl-ad", slug: "thowl-ad",
  title: "Algorithmen & Datenstrukturen",
  description: "TH OWL: Laufzeitanalyse, Sortierverfahren, Listen, Bäume, Graphen, Hashing — mit Original-Klausurfragen.",
  icon: "🔀", color: "#F59E0B", progress: 0, category: "studium",
  lessons: [
    {
      id: "ad-laufzeit", title: "1. Laufzeitanalyse & O-Notation", duration: "30 min", type: "text",
      content: "## Laufzeitanalyse\n\nDie **O-Notation** beschreibt das asymptotische Wachstumsverhalten von Algorithmen.\n\n| Notation | Name | Beispiel |\n|----------|------|----------|\n| $O(1)$ | Konstant | Array-Zugriff |\n| $O(\\\\log n)$ | Logarithmisch | Binäre Suche |\n| $O(n)$ | Linear | Lineare Suche |\n| $O(n \\\\log n)$ | Quasilinear | Mergesort |\n| $O(n^2)$ | Quadratisch | Bubblesort |\n| $O(2^n)$ | Exponentiell | TSP Brute-Force |\n\n**Formal:** $O(f(n)) = \\\\{g(n) \\\\mid \\\\exists c > 0, n_0: \\\\forall n \\\\geq n_0: g(n) \\\\leq c \\\\cdot f(n)\\\\}$\n\n**Rechenregeln:**\n1. $O(c \\\\cdot f) = O(f)$\n2. $O(f + g) = O(\\\\max(f, g))$\n3. Konstanten fallen weg: $O(3n^2 + 100n) = O(n^2)$",
    },
    {
      id: "ad-sortieren", title: "2. Sortierverfahren", duration: "40 min", type: "interactive", interactive: "sortVisualizer",
      content: "## Sortierverfahren\n\n| Verfahren | Best | Average | Worst | Stabil |\n|-----------|------|---------|-------|--------|\n| Bubblesort | $O(n)$ | $O(n^2)$ | $O(n^2)$ | Ja |\n| Insertionsort | $O(n)$ | $O(n^2)$ | $O(n^2)$ | Ja |\n| Selectionsort | $O(n^2)$ | $O(n^2)$ | $O(n^2)$ | Nein |\n| Mergesort | $O(n\\\\log n)$ | $O(n\\\\log n)$ | $O(n\\\\log n)$ | Ja |\n| Quicksort | $O(n\\\\log n)$ | $O(n\\\\log n)$ | $O(n^2)$ | Nein |\n| Heapsort | $O(n\\\\log n)$ | $O(n\\\\log n)$ | $O(n\\\\log n)$ | Nein |\n\n### Quicksort — Divide & Conquer\n\n1. Wähle **Pivotelement**\n2. **Partitioniere:** Elemente < Pivot links, > Pivot rechts\n3. **Rekursion** auf beide Teilarrays\n\n    quicksort(A, lo, hi):\n      if lo < hi:\n        p = partition(A, lo, hi)\n        quicksort(A, lo, p-1)\n        quicksort(A, p+1, hi)\n\n> **Worst-Case:** Sortierte Eingabe + schlechte Pivotwahl → $O(n^2)$. Randomisiertes Pivot oder Median-of-Three vermeidet das.\n\n### Mergesort — Garantiert $O(n \\\\log n)$\n\n1. Teile Array in zwei Hälften\n2. Sortiere beide Hälften rekursiv\n3. **Merge:** Füge sortierte Hälften zusammen",
    },
    {
      id: "ad-datenstrukturen", title: "3. Datenstrukturen: Listen, Stacks, Queues", duration: "35 min", type: "text",
      content: "## Elementare Datenstrukturen\n\n### Verkettete Liste\n\nJedes Element (Knoten) enthält Daten + Zeiger auf nächstes Element.\n\n| Operation | Array | Liste |\n|-----------|-------|-------|\n| Zugriff Index $i$ | $O(1)$ | $O(n)$ |\n| Einfügen Anfang | $O(n)$ | $O(1)$ |\n| Löschen | $O(n)$ | $O(1)^*$ |\n\n**Doppelt verkettet:** Jeder Knoten hat Zeiger auf Vorgänger UND Nachfolger.\n\n### Stack (LIFO)\n\n- **push(x):** Element oben ablegen\n- **pop():** Oberstes Element entfernen\n- **top():** Ansehen ohne Entfernen\n\n### Queue (FIFO)\n\n- **enqueue(x):** Hinten anstellen\n- **dequeue():** Vorne entfernen\n\n### Priority Queue\n\n**extractMax()** entfernt Element mit höchster Priorität. Heap-Implementierung: $O(\\\\log n)$.",
    },
    {
      id: "ad-baeume", title: "4. Bäume & binäre Suchbäume", duration: "40 min", type: "interactive", interactive: "treeExplorer",
      content: "## Bäume — Hierarchische Datenstrukturen\n\n### Binäre Suchbäume (BST)\n\n**Eigenschaft:** Links < Wurzel < Rechts\n\n**Operationen (balanciert):** Suchen/Einfügen/Löschen: $O(\\\\log n)$\n\n**Problem:** BST kann entarten → $O(n)$.\n\n### AVL-Baum (selbst-ausgleichend)\n\n**Balance:** $|\\\\text{Höhe(links)} - \\\\text{Höhe(rechts)}| \\\\leq 1$ für jeden Knoten.\n\n### Traversierung\n\n| Verfahren | Reihenfolge | Anwendung |\n|-----------|-------------|-----------|\n| Preorder | Wurzel → Links → Rechts | Kopie |\n| Inorder | Links → Wurzel → Rechts | Sortiert! |\n| Postorder | Links → Rechts → Wurzel | Löschen |\n| Levelorder | Ebene für Ebene | BFS |\n\n    preorder:  10, 5, 3, 7, 15, 12, 18\n    inorder:   3, 5, 7, 10, 12, 15, 18  ← sortiert!\n    postorder: 3, 7, 5, 12, 18, 15, 10",
    },
    {
      id: "ad-graphen", title: "5. Graphen & Graph-Algorithmen", duration: "40 min", type: "interactive", interactive: "graphExplorer",
      content: "## Graphen\n\nEin **Graph** $G = (V, E)$ besteht aus Knoten und Kanten.\n\n### Darstellung\n\n- **Adjazenzmatrix:** $A[i][j] = 1$ wenn Kante $i \\\\to j$ existiert. $O(|V|^2)$ Speicher.\n- **Adjazenzliste:** Für jeden Knoten Liste der Nachbarn. $O(|V| + |E|)$.\n\n### BFS vs. DFS\n\n**BFS:** Queue, ebenenweise, kürzeste Wege (ungewichtet), $O(|V| + |E|)$\n**DFS:** Stack/Rekursion, tiefensuche, Zyklenerkennung, $O(|V| + |E|)$\n\n### Dijkstra\n\nKürzeste Wege in gewichteten Graphen (positive Kanten):\n\n    dijkstra(G, s):\n      dist[s] = 0, alle anderen = ∞\n      PQ = alle Knoten\n      while PQ nicht leer:\n        u = extractMin(PQ)\n        für jede Kante (u,v) mit Gewicht w:\n          wenn dist[u] + w < dist[v]:\n            dist[v] = dist[u] + w\n\n> Mit Fibonacci-Heap: $O(|E| + |V| \\\\log |V|)$.\n\n### MST (Kruskal & Prim)\n\n**Kruskal:** Sortiere Kanten, füge hinzu wenn kein Zyklus (Union-Find).\n**Prim:** Starte mit Knoten, füge jeweils leichteste Kante zum Rest hinzu.",
    },
    {
      id: "ad-hashing", title: "6. Hashing & Hash-Tabellen", duration: "25 min", type: "text",
      content: "## Hashing\n\nHash-Tabellen: Suchen, Einfügen, Löschen in $O(1)$ average case.\n\n### Hash-Funktionen\n\n- **Divisionsmethode:** $h(k) = k \\\\bmod m$ ($m$ prim)\n- **Multiplikationsmethode:** $h(k) = \\\\lfloor m \\\\cdot (kA \\\\bmod 1) \\\\rfloor$\n\n### Kollisionsbehandlung\n\n1. **Verkettung (Chaining):** Jeder Slot hat eine Liste\n2. **Offene Adressierung:** Lineares/Quadratisches Sondieren, Doppel-Hashing\n\n### Lastfaktor\n\n$\\\\alpha = n/m$ (Elemente / Größe). Empfohlen: $\\\\alpha < 0.75$. Bei Überschreitung: **Rehashing**.",
    },
    {
      id: "ad-klausur", title: "Probeklausur AD — 12 Fragen", duration: "60 min", type: "quiz", examMode: true,
      content: "## AD Probeklausur — 12 Fragen\n\n### Frage 1\nQuicksort Worst-Case bei sortierter Eingabe?\nA) $O(n \\\\log n)$\nB) $O(n^2)$\nC) $O(n)$\nD) $O(\\\\log n)$\n\nRichtig: **B.** Sortierte Eingabe + Pivot = erstes Element → $O(n^2)$.\n\n### Frage 2\nWelche Datenstruktur: LIFO?\nA) Queue\nB) Stack\nC) Priority Queue\nD) Deque\n\nRichtig: **B.** Stack = Last In First Out.\n\n### Frage 3\nBinäre Suche Laufzeit?\nA) $O(n)$\nB) $O(n^2)$\nC) $O(\\\\log n)$\nD) $O(n \\\\log n)$\n\nRichtig: **C.** Halbierung des Suchraums pro Schritt.\n\n### Frage 4\nBST Traversierung für sortierte Ausgabe?\nA) Preorder\nB) Inorder\nC) Postorder\nD) Levelorder\n\nRichtig: **B.** Inorder = Links → Wurzel → Rechts.\n\n### Frage 5\nKürzeste Wege, gewichteter Graph (positiv)?\nA) BFS\nB) DFS\nC) Dijkstra\nD) Kruskal\n\nRichtig: **C.** Dijkstra mit Priority Queue.\n\n### Frage 6\nLastfaktor $\\\\alpha$?\nA) $n+m$\nB) $n \\\\cdot m$\nC) $n/m$\nD) $m/n$\n\nRichtig: **C.** $\\\\alpha = n/m$ (Elemente / Tabellengröße).\n\n### Frage 7\nWelches Sortierverfahren ist NICHT stabil?\nA) Mergesort\nB) Bubblesort\nC) Insertionsort\nD) Quicksort\n\nRichtig: **D.** Quicksort vertauscht über weite Distanzen.\n\n### Frage 8\nAVL-Baum ist...\nA) Hashing-Verfahren\nB) Selbst-ausgleichender BST\nC) Sortierverfahren\nD) Graphalgorithmus\n\nRichtig: **B.** Balance-Faktor $\\\\leq 1$ für jeden Knoten.\n\n### Frage 9\nBFS verwendet...\nA) Stack\nB) Queue\nC) Priority Queue\nD) Hash-Tabelle\n\nRichtig: **B.** BFS = Queue (FIFO).\n\n### Frage 10\nMergesort Average Case?\nA) $O(n)$\nB) $O(n \\\\log n)$\nC) $O(n^2)$\nD) $O(\\\\log n)$\n\nRichtig: **B.** Mergesort garantiert $O(n \\\\log n)$.\n\n### Frage 11\nDAG = ?\nA) Dynamic Array Graph\nB) Directed Acyclic Graph\nC) Distributed Algorithm Generator\nD) Double Access Grid\n\nRichtig: **B.** Gerichteter azyklischer Graph.\n\n### Frage 12\nUnion-Find für...\nA) Sortieren\nB) Kruskals MST\nC) Binäre Suche\nD) Partitionierung\n\nRichtig: **B.** Effiziente Zyklenerkennung in Kruskal.",
    },
  ],
};
