import { Module } from "../types";

export const thowlDBModule: Module = {
  id: "thowl-db", slug: "thowl-db",
  title: "Datenbanken",
  description: "TH OWL: ER-Modelle, Relationale Algebra, SQL, Normalisierung (1NF-3NF), Transaktionen, ACID — mit Original-Klausurfragen.",
  icon: "🗄️", color: "#06B6D4", progress: 0, category: "studium",
  lessons: [
    {
      id: "db-er", title: "1. ER-Modellierung", duration: "30 min", type: "interactive", interactive: "erDiagramBuilder",
      content: "## ER-Modellierung\n\n### Grundbausteine\n\n- **Entity:** Reales/abstraktes Objekt (z.B. Student)\n- **Attribut:** Eigenschaft (z.B. Name, Matrikelnummer)\n- **Relationship:** Verbindung zwischen Entitäten (z.B. 'hört')\n\n### Kardinalitäten\n\n| Typ | Beschreibung | Beispiel |\n|-----|-------------|----------|\n| 1:1 | Genau ein B zu A | Person ↔ Ausweis |\n| 1:n | Mehrere B zu A | Professor ↔ Vorlesung |\n| n:m | Viele zu viele | Student ↔ Vorlesung |\n\n> **n:m braucht eigene Tabelle im relationalen Modell!**\n\n### Schlüssel\n\n- **Primärschlüssel:** Eindeutige ID pro Datensatz\n- **Fremdschlüssel:** Verweis auf Primärschlüssel anderer Tabelle",
    },
    {
      id: "db-relational", title: "2. Relationales Modell & Algebra", duration: "35 min", type: "interactive", interactive: "relationalModelExplorer",
      content: "## Relationale Algebra\n\nGrundoperationen auf Relationen:\n\n| Operation | Symbol | SQL |\n|-----------|--------|-----|\n| Selektion | $\\\\sigma_{Bed}(R)$ | WHERE |\n| Projektion | $\\\\pi_{Spalten}(R)$ | SELECT |\n| Vereinigung | $R \\\\cup S$ | UNION |\n| Differenz | $R \\\\setminus S$ | EXCEPT |\n| Kreuzprodukt | $R \\\\times S$ | CROSS JOIN |\n| Join | $R \\\\bowtie_{Bed} S$ | JOIN ON |\n\n### Join-Arten\n\n- **Natural Join:** Gleiche Spaltennamen automatisch verknüpft\n- **Inner Join:** Nur gematchte Zeilen\n- **Left Outer Join:** Alle linken + passende rechte\n- **Full Outer Join:** Alle aus beiden",
    },
    {
      id: "db-sql", title: "3. SQL", duration: "40 min", type: "interactive", interactive: "sqlPlayground",
      content: "## SQL\n\n### Wichtige Befehle\n\n    CREATE TABLE Studenten (\n      MatrNr    INTEGER PRIMARY KEY,\n      Name      VARCHAR(50) NOT NULL,\n      Semester  INTEGER CHECK (Semester >= 1)\n    );\n\n    INSERT INTO Studenten VALUES (12345, 'Max', 3);\n\n    SELECT Name, Semester\n    FROM Studenten\n    WHERE Semester >= 3\n    ORDER BY Name ASC;\n\n    SELECT s.Name, p.Note\n    FROM Studenten s\n    JOIN Pruefungen p ON s.MatrNr = p.MatrNr\n    WHERE p.Fach = 'Datenbanken';\n\n    UPDATE Studenten SET Semester = Semester + 1;\n    DELETE FROM Studenten WHERE MatrNr = 12345;\n\n### Aggregatfunktionen\n\n| Funktion | Beschreibung |\n|----------|-------------|\n| COUNT(*) | Anzahl Zeilen |\n| COUNT(DISTINCT x) | Verschiedene Werte |\n| SUM(x) | Summe |\n| AVG(x) | Durchschnitt |\n| MIN(x), MAX(x) | Minimum/Maximum |\n\n### SQL-Klauseln (Reihenfolge!)\n\n    SELECT   -- Projektion\n    FROM     -- Quelle\n    WHERE    -- Selektion (VOR Gruppierung)\n    GROUP BY -- Gruppierung\n    HAVING   -- Filter NACH Gruppierung\n    ORDER BY -- Sortierung",
    },
    {
      id: "db-normalisierung", title: "4. Normalisierung (1NF-3NF)", duration: "35 min", type: "interactive", interactive: "normalisationTrainer",
      content: "## Normalisierung\n\n### 1NF: Atomare Attributwerte\n\nKeine Wiederholungsgruppen, keine mehrwertigen Attribute.\n\n### 2NF: Volle funktionale Abhängigkeit\n\n1NF + jedes Nichtschlüsselattribut hängt vom GESAMTEN Primärschlüssel ab.\n\n❌ Tabelle Prüfung(MatrNr, FachNr, Note, Fachname): Fachname hängt nur von FachNr ab (partielle Abhängigkeit).\n✅ Aufteilen in Prüfung(MatrNr, FachNr, Note) und Fach(FachNr, Fachname).\n\n### 3NF: Keine transitiven Abhängigkeiten\n\n2NF + kein Nichtschlüsselattribut hängt von anderem Nichtschlüsselattribut ab.\n\n❌ Mitarbeiter(PersNr, Name, AbtNr, AbtName): AbtName hängt von AbtNr, nicht direkt von PersNr.\n✅ Aufteilen in Mitarbeiter(PersNr, Name, AbtNr) und Abteilung(AbtNr, AbtName).\n\n### Merksatz\n\n> Jedes Attribut muss eine Tatsache über den Schlüssel, den ganzen Schlüssel und nichts als den Schlüssel sein. — William Kent",
    },
    {
      id: "db-transaktionen", title: "5. Transaktionen & ACID", duration: "25 min", type: "text",
      content: "## Transaktionen & ACID\n\n| Prinzip | Bedeutung |\n|---------|-----------|\n| **A**tomicity | Alles oder nichts |\n| **C**onsistency | Integrität erhalten |\n| **I**solation | Nebenläufige Transaktionen isoliert |\n| **D**urability | Dauerhaft gespeichert |\n\n### Isolation Levels\n\n| Level | Dirty Read | Non-Repeatable | Phantom |\n|-------|-----------|---------------|--------|\n| READ UNCOMMITTED | Ja | Ja | Ja |\n| READ COMMITTED | Nein | Ja | Ja |\n| REPEATABLE READ | Nein | Nein | Ja |\n| SERIALIZABLE | Nein | Nein | Nein |\n\n### SQL-Transaktion\n\n    BEGIN TRANSACTION;\n      UPDATE Konto SET Saldo = Saldo - 100 WHERE Nr = 1;\n      UPDATE Konto SET Saldo = Saldo + 100 WHERE Nr = 2;\n    COMMIT;  -- oder ROLLBACK",
    },
    {
      id: "db-klausur", title: "Probeklausur DB — 12 Fragen", duration: "60 min", type: "quiz", examMode: true,
      content: "## DB Probeklausur — 12 Fragen\n\n### Frage 1\nWelche Normalform: atomare Attributwerte?\nA) 2NF\nB) 3NF\nC) 1NF\nD) BCNF\n\nRichtig: **C.** 1NF = atomare Werte.\n\n### Frage 2\n'I' in ACID?\nA) Integration\nB) Isolation\nC) Index\nD) Inheritance\n\nRichtig: **B.** Isolation.\n\n### Frage 3\nFilter NACH Gruppierung?\nA) WHERE\nB) HAVING\nC) FILTER\nD) GROUP BY\n\nRichtig: **B.** WHERE vor, HAVING nach GROUP BY.\n\n### Frage 4\nn:m-Beziehung im relationalen Modell?\nA) Fremdschlüssel in einer Tabelle\nB) Neue Tabelle mit zwei Fremdschlüsseln\nC) Array\nD) Geht nicht\n\nRichtig: **B.** Verbindungstabelle mit kombiniertem PK.\n\n### Frage 5\nLEFT OUTER JOIN liefert...\nA) Nur gematchte\nB) Alle linken + passende rechte\nC) Alle rechten + passende linke\nD) Kreuzprodukt\n\nRichtig: **B.**\n\n### Frage 6\n$\\\\pi_{A,B}(\\\\sigma_{C>5}(R))$ — Reihenfolge?\nA) Projektion, dann Selektion\nB) Selektion, dann Projektion\nC) Gleichzeitig\nD) Beliebig\n\nRichtig: **B.** Von innen nach außen.\n\n### Frage 7\nDirty Reads verhindert ab...\nA) READ UNCOMMITTED\nB) READ COMMITTED\nC) REPEATABLE READ\nD) SERIALIZABLE\n\nRichtig: **B.**\n\n### Frage 8\nFremdschlüssel referenziert...\nA) Beliebigen Wert\nB) Primärschlüssel\nC) Index\nD) NULL\n\nRichtig: **B.** FK → PK.\n\n### Frage 9\nVerschiedene Werte zählen?\nA) COUNT(*)\nB) COUNT(DISTINCT x)\nC) SUM(x)\nD) AVG(x)\n\nRichtig: **B.**\n\n### Frage 10\nTransitive Abhängigkeit = Verletzung von...\nA) 1NF\nB) 2NF\nC) 3NF\nD) Keine\n\nRichtig: **C.** Nichtschlüssel → Nichtschlüssel.\n\n### Frage 11\nTransaktion rückgängig?\nA) COMMIT\nB) UNDO\nC) ROLLBACK\nD) REVERT\n\nRichtig: **C.**\n\n### Frage 12\nNatural Join vs Inner Join?\nA) Gleich\nB) Natural: automatisch über gleichnamige Spalten\nC) Inner ist schneller\nD) Natural nur Postgres\n\nRichtig: **B.**",
    },
  ],
};
