import { Module } from "../types";

export const thowlEnglischModule: Module = {
  id: "thowl-englisch", slug: "thowl-englisch",
  title: "Technical English",
  description: "TH OWL: Reading Comprehension, False Cognates, Technical Vocabulary, Listening Comprehension, Scientific Writing — mit Übungen aus Original-Materialien.",
  icon: "🇬🇧", color: "#3B82F6", progress: 0, category: "studium",
  lessons: [
    {
      id: "eng-false-cognates", title: "1. False Cognates — False Friends", duration: "25 min", type: "text",
      content: "## False Cognates\n\nWörter, die ähnlich klingen aber unterschiedliche Bedeutung haben.\n\n### Häufige False Friends\n\n| Deutsch | Englische Verwechslung | Tatsächliche Bedeutung | Richtig |\n|---------|----------------------|----------------------|--------|\n| bekommen | become | werden | receive, get |\n| aktuell | actual | tatsächlich | current |\n| sensibel | sensible | vernünftig | sensitive |\n| Gift | gift | Geschenk | poison |\n| Fabrik | fabric | Stoff | factory |\n| Chef | chef | Koch | boss |\n| Mappe | map | Landkarte | folder |\n| Rat | rat | Ratte | advice |\n| Brand | brand | Marke | fire |\n\n### Technisch besonders gefährlich\n\n| Deutsch | Falsch | Richtig |\n|---------|--------|--------|\n| Steuerung | taxation | control |\n| Regler | ruler | controller |\n| Leitung | guidance | cable/line |\n| Auflösung | dissolution | resolution |\n\n> 'I become a gift from my chef' = 'Ich WERDE ein Geschenk von meinem Koch'!",
    },
    {
      id: "eng-reading", title: "2. Reading Comprehension", duration: "30 min", type: "text",
      content: "## Reading Comprehension\n\n### Skimming vs. Scanning\n\n- **Skimming:** Überfliegen für Hauptthema (Überschriften, erste/letzte Sätze)\n- **Scanning:** Gezielt nach Information suchen (Zahlen, Namen, Keywords)\n\n### Typische Fragetypen\n\n1. **Main Idea:** Worum geht es hauptsächlich?\n2. **Detail:** Welche Aussage ist laut Text richtig?\n3. **Inference:** Was kann man schließen?\n4. **Vocabulary:** Was bedeutet Wort X in Zeile Y?\n5. **Author's Purpose:** Was ist die Absicht des Autors?\n\n### Signalwörter\n\n| Funktion | Wörter |\n|----------|--------|\n| Kontrast | however, but, although, whereas |\n| Ursache/Wirkung | therefore, thus, consequently, because |\n| Aufzählung | first, furthermore, moreover, in addition |\n| Beispiel | for example, such as, e.g. |\n| Zusammenfassung | in conclusion, to summarize, overall |",
    },
    {
      id: "eng-listening", title: "3. Listening Comprehension", duration: "25 min", type: "text",
      content: "## Listening Comprehension\n\n### Strategien\n\n1. **Vor dem Hören:** Thema identifizieren, Vorwissen aktivieren\n2. **Während:** Keywords notieren, nicht jedes Wort verstehen wollen\n3. **Nachher:** Notizen strukturieren\n\n### Technische Akronyme\n\n| Akronym | Bedeutung |\n|---------|----------|\n| R&D | Research and Development |\n| POC | Proof of Concept |\n| MVP | Minimum Viable Product |\n| API | Application Programming Interface |\n| IoT | Internet of Things |\n| AI/ML | Artificial Intelligence / Machine Learning |\n| QA | Quality Assurance |\n| CI/CD | Continuous Integration / Deployment |\n\n### Cornell-Notizmethode\n\nBlatt in 3 Bereiche: Keywords (links), Notes (rechts), Summary (unten).\nWährend Vorlesung: rechte Spalte. Danach: Keywords + Summary ergänzen.",
    },
    {
      id: "eng-vocabulary", title: "4. Technical Vocabulary", duration: "30 min", type: "text",
      content: "## Fachwortschatz\n\n### Informatik\n\n| Deutsch | Englisch |\n|---------|----------|\n| Anforderung | requirement |\n| Schnittstelle | interface |\n| Laufzeit | runtime |\n| Speicher | memory (RAM) / storage (HDD) |\n| Datenbank | database |\n| Netzwerk | network |\n| Schicht | layer |\n| Verschlüsselung | encryption |\n| Verfahren | method / procedure |\n| Zuverlässigkeit | reliability |\n| Verfügbarkeit | availability |\n| Wartbarkeit | maintainability |\n\n### Mathematik\n\n| Deutsch | Englisch |\n|---------|----------|\n| Gleichung | equation |\n| Ableitung | derivative |\n| Integral | integral |\n| Grenzwert | limit |\n| Beweis | proof |\n| Menge | set |\n| Eigenwert | eigenvalue |\n| Wahrscheinlichkeit | probability |\n\n### Präsentations-Phrasen\n\n**Einleitung:** 'Good morning everyone. Today I'd like to talk about...'\n**Übergang:** 'Moving on to the next point...'\n**Fazit:** 'To sum up... / In conclusion...'\n**Fragen:** 'That's an interesting question. Does that answer your question?'",
    },
    {
      id: "eng-scientific", title: "5. Scientific Writing", duration: "25 min", type: "text",
      content: "## Scientific Writing\n\n### IMRaD-Struktur\n\n| Section | Inhalt |\n|---------|--------|\n| **I**ntroduction | Warum? Kontext, Ziel |\n| **M**ethods | Wie? Aufbau, Algorithmus |\n| **R**esults | Was kam raus? Daten |\n| **D**iscussion | Was bedeutet das? |\n\n### Abstract (~200 Wörter)\n\n1. Background (1-2 Sätze)\n2. Problem/Forschungslücke\n3. Method\n4. Wichtigste Results\n5. Conclusion\n\n### Active vs. Passive Voice\n\n- Traditionell: 'The experiment was conducted...'\n- Modern: 'We conducted the experiment...'\n\n> Moderne Papers bevorzugen Active Voice — klarer und direkter.\n\n### Häufige Fehler (Deutsche Muttersprachler)\n\n- 'The data is...' → 'The data are...' (Plural)\n- 'This allows to...' → 'This allows us to...'\n- 'As already mentioned...' → 'As mentioned above...'",
    },
    {
      id: "eng-klausur", title: "Übungstest — 15 Fragen", duration: "45 min", type: "quiz", examMode: true,
      content: "## Technical English — Übungstest\n\n### Frage 1\n'bekommen' auf Englisch?\nA) to become\nB) to receive\nC) to arrive\nD) to belong\n\nRichtig: **B.** Become = werden.\n\n### Frage 2\n'Fabrik' = ?\nA) fabric\nB) factory\nC) fabrication\nD) fabulous\n\nRichtig: **B.** Fabric = Stoff.\n\n### Frage 3\n'aktuell' = ?\nA) actual\nB) current\nC) acute\nD) accurate\n\nRichtig: **B.** Actual = tatsächlich.\n\n### Frage 4\nIMRaD = ?\nA) Internet, Media, Radio, Data\nB) Introduction, Methods, Results, Discussion\nC) Information, Measurement, R&D\nD) Input, Modification, Retrieval, Deletion\n\nRichtig: **B.**\n\n### Frage 5\n'Regler' technisch = ?\nA) ruler\nB) regulator\nC) controller\nD) register\n\nRichtig: **C.** Ruler = Lineal.\n\n### Frage 6\nKontrast-Signalwort?\nA) furthermore\nB) therefore\nC) however\nD) moreover\n\nRichtig: **C.**\n\n### Frage 7\n'Zuverlässigkeit' = ?\nA) reliability\nB) availability\nC) responsibility\nD) maintainability\n\nRichtig: **A.** MTBF.\n\n### Frage 8\nModern Scientific Writing bevorzugt...\nA) Passive Voice\nB) Active Voice\nC) Deutsche Satzstellung\nD) Nur Passive\n\nRichtig: **B.**\n\n### Frage 9\n'Gift' auf Englisch?\nA) gift\nB) poison\nC) donation\nD) lift\n\nRichtig: **B.** Gift (EN) = Geschenk!\n\n### Frage 10\nAPI = ?\nA) Automated Processing Interface\nB) Application Programming Interface\nC) Advanced Protocol Integration\nD) Application Process Integration\n\nRichtig: **B.**\n\n### Frage 11\n'The data...' korrekt?\nA) is\nB) are\nC) am\nD) be\n\nRichtig: **B.** Data = Plural von datum.\n\n### Frage 12\n'eventuell' = ?\nA) eventually\nB) possibly\nC) evenly\nD) every time\n\nRichtig: **B.** Eventually = schließlich.\n\n### Frage 13\nCornell Method für...\nA) Kochen\nB) Notizen machen\nC) Programmieren\nD) Fertigung\n\nRichtig: **B.**\n\n### Frage 14\n'Leistung' (elektrisch) = ?\nA) performance\nB) power\nC) leadership\nD) leakage\n\nRichtig: **B.** Power (Watt).\n\n### Frage 15\nCI/CD = ?\nA) Computer Integration / Design\nB) Continuous Integration / Deployment\nC) Central Information / Database\nD) Core Infrastructure / Development\n\nRichtig: **B.**",
    },
  ],
};
